"""Type stubs for the native stegoeggo binding module."""

from typing import Optional

class StegoEggoError(Exception): ...

class RightsPolicy:
    Unspecified: "RightsPolicy"
    Allowed: "RightsPolicy"
    ProhibitedAiMlTraining: "RightsPolicy"
    ProhibitedGenerativeAiTraining: "RightsPolicy"
    ProhibitedExceptSearchIndexing: "RightsPolicy"
    ProhibitedAllDataMining: "RightsPolicy"
    ProhibitedSeeConstraints: "RightsPolicy"
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class DmiValue:
    Unspecified: "DmiValue"
    Allowed: "DmiValue"
    ProhibitedAiMlTraining: "DmiValue"
    ProhibitedGenAiMlTraining: "DmiValue"
    ProhibitedExceptSearchEngineIndexing: "DmiValue"
    Prohibited: "DmiValue"
    ProhibitedSeeConstraints: "DmiValue"
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ImageOutputFormat:
    Png: "ImageOutputFormat"
    Jpeg: "ImageOutputFormat"
    WebP: "ImageOutputFormat"
    @staticmethod
    def from_extension(ext: str) -> Optional["ImageOutputFormat"]: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class MetadataUpdatePolicy:
    ReplaceStegoOwned: "MetadataUpdatePolicy"
    FailOnConflict: "MetadataUpdatePolicy"
    PreserveExisting: "MetadataUpdatePolicy"
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ProtectionPreset:
    LegalNotice: "ProtectionPreset"
    LegalNoticeWithStego: "ProtectionPreset"
    AuthenticatedProvenance: "ProtectionPreset"
    Maximal: "ProtectionPreset"
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class AuthenticationMode:
    None_: "AuthenticationMode"  # name 'None' is reserved in Python; use None_ as alias
    Hmac: "AuthenticationMode"
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class HiddenMarkerMode:
    @staticmethod
    def disabled() -> "HiddenMarkerMode": ...
    @staticmethod
    def seed_only() -> "HiddenMarkerMode": ...
    @staticmethod
    def best_effort() -> "HiddenMarkerMode": ...
    @staticmethod
    def tiled(tile_size: int) -> "HiddenMarkerMode": ...
    @property
    def is_tiled(self) -> bool: ...
    @property
    def tile_size(self) -> Optional[int]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class RightsNotice:
    def __init__(self) -> None: ...
    def with_copyright_holder(self, holder: str) -> "RightsNotice": ...
    def with_copyright_owner(self, owner: str) -> "RightsNotice": ...
    def with_contact_email(self, email: str) -> "RightsNotice": ...
    def with_license_url(self, url: str) -> "RightsNotice": ...
    def with_usage_terms(self, terms: str) -> "RightsNotice": ...
    def with_creation_date(self, date: str) -> "RightsNotice": ...
    def with_ai_constraints(self, constraints: str) -> "RightsNotice": ...
    def with_web_statement_of_rights(self, statement: str) -> "RightsNotice": ...
    def with_creator(self, creator: str) -> "RightsNotice": ...
    def with_credit_line(self, line: str) -> "RightsNotice": ...
    def with_licensor_name(self, name: str) -> "RightsNotice": ...
    def with_licensor_email(self, email: str) -> "RightsNotice": ...
    def with_licensor_url(self, url: str) -> "RightsNotice": ...
    def with_metadata_date(self, date: str) -> "RightsNotice": ...
    def with_notice_applied_at(self, timestamp: str) -> "RightsNotice": ...
    def with_dmi(self, dmi: DmiValue) -> "RightsNotice": ...
    @property
    def copyright_holder(self) -> Optional[str]: ...
    @property
    def copyright_owner(self) -> Optional[str]: ...
    @property
    def contact_email(self) -> Optional[str]: ...
    @property
    def license_url(self) -> Optional[str]: ...
    @property
    def usage_terms(self) -> Optional[str]: ...
    @property
    def creation_date(self) -> Optional[str]: ...
    @property
    def ai_constraints(self) -> Optional[str]: ...
    @property
    def web_statement_of_rights(self) -> Optional[str]: ...
    @property
    def creator(self) -> Optional[str]: ...
    @property
    def credit_line(self) -> Optional[str]: ...
    @property
    def licensor_name(self) -> Optional[str]: ...
    @property
    def licensor_email(self) -> Optional[str]: ...
    @property
    def licensor_url(self) -> Optional[str]: ...
    @property
    def metadata_date(self) -> Optional[str]: ...
    @property
    def notice_applied_at(self) -> Optional[str]: ...
    @property
    def dmi(self) -> Optional[DmiValue]: ...
    @property
    def seed(self) -> Optional[int]: ...
    @property
    def has_legal_content(self) -> bool: ...
    def __repr__(self) -> str: ...

class ProcessingOptions:
    def __init__(self) -> None: ...
    def with_output_format(self, format: ImageOutputFormat) -> "ProcessingOptions": ...
    def with_jpeg_quality(self, quality: int) -> "ProcessingOptions": ...
    def with_progressive_jpeg(self) -> "ProcessingOptions": ...
    def with_max_dimension(self, max: int) -> "ProcessingOptions": ...
    def with_metadata_update_policy(self, policy: MetadataUpdatePolicy) -> "ProcessingOptions": ...
    def with_stego_redundancy(self, redundancy: int) -> "ProcessingOptions": ...
    def with_content_hash(self, hash: bytes) -> "ProcessingOptions": ...
    def with_timestamp_override(self, timestamp: str) -> "ProcessingOptions": ...
    def __repr__(self) -> str: ...

class ResourceLimits:
    @staticmethod
    def defaults() -> "ResourceLimits": ...
    @staticmethod
    def builder() -> "ResourceLimitsBuilder": ...
    def __repr__(self) -> str: ...

class ResourceLimitsBuilder:
    def with_max_input_bytes(self, val: int) -> "ResourceLimitsBuilder": ...
    def with_max_width(self, val: int) -> "ResourceLimitsBuilder": ...
    def with_max_height(self, val: int) -> "ResourceLimitsBuilder": ...
    def with_max_png_chunks(self, val: int) -> "ResourceLimitsBuilder": ...
    def with_max_jpeg_segments(self, val: int) -> "ResourceLimitsBuilder": ...
    def with_max_webp_riff_chunks(self, val: int) -> "ResourceLimitsBuilder": ...
    def with_max_xmp_bytes(self, val: int) -> "ResourceLimitsBuilder": ...
    def with_max_metadata_fields(self, val: int) -> "ResourceLimitsBuilder": ...
    def with_max_metadata_field_bytes(self, val: int) -> "ResourceLimitsBuilder": ...
    def with_max_payload_bytes(self, val: int) -> "ResourceLimitsBuilder": ...
    def with_max_tile_extraction_origins(self, val: int) -> "ResourceLimitsBuilder": ...
    def with_max_verification_seeds(self, val: int) -> "ResourceLimitsBuilder": ...
    def build(self) -> ResourceLimits: ...

class ProtectionRequest:
    @staticmethod
    def metadata_only(notice: RightsNotice, policy: RightsPolicy) -> "ProtectionRequest": ...
    @staticmethod
    def with_hidden_marker(notice: RightsNotice, policy: RightsPolicy) -> "ProtectionRequest": ...
    @staticmethod
    def from_preset(
        preset: ProtectionPreset,
        notice: RightsNotice,
        policy: RightsPolicy,
    ) -> "ProtectionRequest": ...
    def with_seed(self, seed: int) -> "ProtectionRequest": ...
    def with_intensity(self, intensity: float) -> "ProtectionRequest": ...
    def with_output_format(self, format: ImageOutputFormat) -> "ProtectionRequest": ...
    def with_jpeg_quality(self, quality: int) -> "ProtectionRequest": ...
    def with_progressive_jpeg(self) -> "ProtectionRequest": ...
    def with_max_dimension(self, max: int) -> "ProtectionRequest": ...
    def with_metadata_update_policy(self, policy: MetadataUpdatePolicy) -> "ProtectionRequest": ...
    def with_stego_redundancy(self, redundancy: int) -> "ProtectionRequest": ...
    def with_content_hash(self, hash: bytes) -> "ProtectionRequest": ...
    def with_timestamp_override(self, timestamp: str) -> "ProtectionRequest": ...
    def with_processing(self, processing: ProcessingOptions) -> "ProtectionRequest": ...
    def with_mac_key(self, key: bytes) -> "ProtectionRequest": ...
    def with_resource_limits(self, limits: ResourceLimits) -> "ProtectionRequest": ...
    @property
    def policy(self) -> RightsPolicy: ...
    @property
    def seed(self) -> Optional[int]: ...
    @property
    def intensity(self) -> float: ...
    @property
    def has_mac_key(self) -> bool: ...
    def __repr__(self) -> str: ...

class ProtectionWarning:
    MissingMacKey: "ProtectionWarning"
    MetadataInjectionDisabled: "ProtectionWarning"
    ProgressiveJpegFallback: "ProtectionWarning"
    JpegReencodeFragile: "ProtectionWarning"
    LsbCapacitySkipped: "ProtectionWarning"
    DctCapacityInsufficient: "ProtectionWarning"
    ContradictoryLegalClaims: "ProtectionWarning"
    MissingRightsConstraints: "ProtectionWarning"
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ExecutionReport:
    @property
    def effective_policy(self) -> RightsPolicy: ...
    @property
    def effective_dmi(self) -> Optional[DmiValue]: ...
    @property
    def metadata_injected(self) -> bool: ...
    @property
    def stego_attempted(self) -> bool: ...
    @property
    def stego_succeeded(self) -> bool: ...
    @property
    def format_transcoded(self) -> bool: ...
    @property
    def warnings(self) -> list[ProtectionWarning]: ...
    @property
    def has_degradation(self) -> bool: ...
    @property
    def any_succeeded(self) -> bool: ...
    @property
    def resource_usage(self) -> Optional[ResourceUsage]: ...
    def __repr__(self) -> str: ...

class ResourceUsage:
    @property
    def input_bytes(self) -> int: ...
    @property
    def png_chunks_scanned(self) -> int: ...
    @property
    def jpeg_segments_scanned(self) -> int: ...
    @property
    def webp_riff_chunks_scanned(self) -> int: ...
    @property
    def xmp_bytes_parsed(self) -> int: ...
    @property
    def metadata_fields_extracted(self) -> int: ...
    @property
    def metadata_bytes_copied(self) -> int: ...
    @property
    def tile_origins_checked(self) -> int: ...
    @property
    def verification_seeds_tried(self) -> int: ...
    @property
    def peak_allocations_bytes(self) -> int: ...
    def __repr__(self) -> str: ...

class VerificationStatus:
    Verified: "VerificationStatus"
    Invalid: "VerificationStatus"
    NotFound: "VerificationStatus"
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class EvidenceStrength:
    NoNoticeFound: "EvidenceStrength"
    MetadataNoticeOnly: "EvidenceStrength"
    MetadataNoticeAndBestEffortStego: "EvidenceStrength"
    MetadataNoticeAndAuthenticatedProvenance: "EvidenceStrength"
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class VerificationReport:
    @property
    def status(self) -> VerificationStatus: ...
    @property
    def evidence_strength(self) -> EvidenceStrength: ...
    @property
    def has_errors(self) -> bool: ...
    @property
    def hidden_marker_status(self) -> VerificationStatus: ...
    @property
    def hidden_marker_seed(self) -> Optional[int]: ...
    @property
    def hidden_marker_payload_version(self) -> Optional[int]: ...
    @property
    def hidden_marker_intensity(self) -> Optional[float]: ...
    @property
    def hidden_marker_tiled(self) -> bool: ...
    @property
    def rights_found(self) -> bool: ...
    @property
    def copyright_holder(self) -> Optional[str]: ...
    @property
    def creator(self) -> Optional[str]: ...
    @property
    def contact(self) -> Optional[str]: ...
    @property
    def rights_url(self) -> Optional[str]: ...
    @property
    def usage_terms(self) -> Optional[str]: ...
    @property
    def ai_constraints(self) -> Optional[str]: ...
    @property
    def rights_dmi(self) -> Optional[int]: ...
    @property
    def authentication_attempted(self) -> bool: ...
    @property
    def authentication_key_matched(self) -> bool: ...
    @property
    def authentication_hmac_status(self) -> Optional[VerificationStatus]: ...
    @property
    def trust_trusted(self) -> bool: ...
    @property
    def trust_reason(self) -> str: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

def detect_format(data: bytes) -> Optional[str]: ...
def protect(data: bytes, request: ProtectionRequest) -> bytes: ...
def protect_with_warnings(
    data: bytes, request: ProtectionRequest
) -> tuple[bytes, list[ProtectionWarning]]: ...
def protect_with_report(
    data: bytes, request: ProtectionRequest
) -> tuple[bytes, ExecutionReport]: ...
def verify(
    data: bytes,
    mac_key: Optional[bytes] = ...,
    resource_limits: Optional[ResourceLimits] = ...,
) -> VerificationReport: ...
def protect_file(path: str, request: ProtectionRequest) -> None: ...
def verify_file(
    path: str,
    mac_key: Optional[bytes] = ...,
    resource_limits: Optional[ResourceLimits] = ...,
) -> VerificationReport: ...

__version__: str
__stegoeggo_version__: str
