use super::*;
use serde::{Deserialize, Serialize};

/// Evidence profile controlling the interpretation of protection warnings
/// and the default evidence posture.
///
/// An evidence profile answers the question "what evidence model is the caller
/// trying to express?" while [`ProtectionLevel`] answers "how much processing
/// should occur?"
///
/// - [`LegalNotice`](Self::LegalNotice): Standards-aligned metadata notice.
///   No MAC key required.
/// - [`LegalNoticeWithStego`](Self::LegalNoticeWithStego): Metadata notice
///   plus best-effort hidden marker. No MAC key required.
/// - [`AuthenticatedProvenance`](Self::AuthenticatedProvenance): Cryptographic
///   proof that a hidden payload was generated by a party with the configured
///   key. MAC key expected.
/// - [`Maximal`](Self::Maximal): All available legal notice and evidence channels.
#[deprecated(
    since = "0.4.0",
    note = "Use ProtectionPreset instead. EvidenceProfile only changes warning interpretation; ProtectionPreset controls actual processing behavior."
)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[non_exhaustive]
pub enum EvidenceProfile {
    /// Standards-aligned metadata notice. No MAC key required.
    /// Missing MAC is not a warning.
    #[default]
    LegalNotice,
    /// Metadata notice plus best-effort hidden marker.
    /// No MAC key required. Stego capacity warnings are best-effort, not
    /// legal-notice failures.
    LegalNoticeWithStego,
    /// Cryptographic proof that a hidden payload was generated by a party
    /// with the configured key. MAC key expected; missing MAC is a warning.
    AuthenticatedProvenance,
    /// All available legal notice and evidence channels.
    /// MAC key used if provided; missing MAC is informational.
    Maximal,
}

#[allow(deprecated)]
impl EvidenceProfile {
    /// Returns the lowercase string representation of this evidence profile.
    #[must_use]
    pub fn as_str(&self) -> &'static str {
        match self {
            EvidenceProfile::LegalNotice => "legal-notice",
            EvidenceProfile::LegalNoticeWithStego => "legal-notice-stego",
            EvidenceProfile::AuthenticatedProvenance => "authenticated-provenance",
            EvidenceProfile::Maximal => "maximal",
        }
    }
}

/// Policy for updating metadata on repeated image processing.
///
/// Controls how the protection pipeline handles existing metadata when
/// re-processing an already-protected image.
///
/// # Caveats
///
/// Ownership on PNG is detected by `tEXt`/`iTXt` keyword alone (no namespace).
/// Common keywords like `Copyright`, `Creator`, `UsageTerms`, and
/// `License` may already appear in user-authored PNGs produced by other
/// tools. With `ReplaceStegoOwned`, those chunks are removed before
/// re-injection; with `FailOnConflict`, processing aborts. JPEG and WebP
/// ownership is more precise (structured COM, namespaced XMP, RIFF chunk
/// IDs) and is not affected by this caveat.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[non_exhaustive]
pub enum MetadataUpdatePolicy {
    /// Replace all StegoEggo-owned metadata properties. Preserve unrelated
    /// metadata (camera EXIF, color profiles, etc.). This is the default.
    #[default]
    ReplaceStegoOwned,
    /// Fail with an error if conflicting StegoEggo metadata already exists.
    FailOnConflict,
    /// Preserve existing StegoEggo metadata and only add new fields.
    /// Never overwrites existing values.
    PreserveExisting,
}

impl MetadataUpdatePolicy {
    /// Returns the lowercase string representation of this policy.
    #[must_use]
    pub fn as_str(&self) -> &'static str {
        match self {
            MetadataUpdatePolicy::ReplaceStegoOwned => "replace-stego-owned",
            MetadataUpdatePolicy::FailOnConflict => "fail-on-conflict",
            MetadataUpdatePolicy::PreserveExisting => "preserve-existing",
        }
    }
}

impl std::fmt::Display for MetadataUpdatePolicy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            MetadataUpdatePolicy::ReplaceStegoOwned => write!(f, "ReplaceStegoOwned"),
            MetadataUpdatePolicy::FailOnConflict => write!(f, "FailOnConflict"),
            MetadataUpdatePolicy::PreserveExisting => write!(f, "PreserveExisting"),
        }
    }
}

/// Protection level determining the protection strategy applied to images.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[non_exhaustive]
pub enum ProtectionLevel {
    /// No protection applied.
    Disabled,
    /// Metadata injection with minimal steganography.
    Light,
    /// Full steganography + metadata injection (default).
    #[default]
    Standard,
}

impl ProtectionLevel {
    /// Returns the lowercase string representation of this protection level.
    #[must_use]
    pub fn as_str(&self) -> &'static str {
        match self {
            ProtectionLevel::Disabled => "disabled",
            ProtectionLevel::Light => "light",
            ProtectionLevel::Standard => "standard",
        }
    }

    /// Encodes this protection level as a single byte for payload serialization.
    #[must_use]
    pub fn to_byte(&self) -> u8 {
        match self {
            ProtectionLevel::Disabled => 0,
            ProtectionLevel::Light => 1,
            ProtectionLevel::Standard => 2,
        }
    }

    /// Decodes a protection level from a byte. Returns `None` for unknown values.
    #[must_use]
    pub fn from_byte(b: u8) -> Option<Self> {
        match b {
            0 => Some(ProtectionLevel::Disabled),
            1 => Some(ProtectionLevel::Light),
            2 => Some(ProtectionLevel::Standard),
            _ => None,
        }
    }

    /// Returns the default [`RightsPolicy`] for this legacy protection level.
    ///
    /// This is the single canonical compatibility mapping used by both the CLI
    /// and the library when translating a level into policy. `Light` maps to
    /// `Unspecified` because processing intensity must not silently create an
    /// all-data-mining legal restriction.
    #[must_use]
    pub fn default_policy(self) -> RightsPolicy {
        match self {
            ProtectionLevel::Disabled | ProtectionLevel::Light => RightsPolicy::Unspecified,
            ProtectionLevel::Standard => RightsPolicy::ProhibitedAiMlTraining,
        }
    }

    /// Converts this legacy protection level into a [`ProtectionRequest`] template.
    ///
    /// This is a compatibility adapter for callers migrating from the level-based API.
    /// The returned request has default processing options and no legal metadata —
    /// callers should chain builder methods to add notice, policy, and metadata.
    #[must_use]
    pub fn to_request(&self, notice: RightsNotice, policy: RightsPolicy) -> ProtectionRequest {
        match self {
            ProtectionLevel::Disabled => {
                // Disabled: metadata-only with no channels
                ProtectionRequest::new(
                    notice,
                    policy,
                    ProtectionChannels {
                        rights_metadata: false,
                        hidden_marker: HiddenMarkerMode::Disabled,
                        authentication: AuthenticationMode::None,
                    },
                )
            }
            ProtectionLevel::Light => {
                // Light: metadata + minimal seed stego (Q-table for JPEG, fixed-position LSB for PNG/WebP)
                ProtectionRequest::new(
                    notice,
                    policy,
                    ProtectionChannels {
                        rights_metadata: true,
                        hidden_marker: HiddenMarkerMode::SeedOnly,
                        authentication: AuthenticationMode::None,
                    },
                )
            }
            ProtectionLevel::Standard => {
                // Standard: full stego + metadata
                ProtectionRequest::new(notice, policy, ProtectionChannels::with_hidden_marker())
            }
        }
    }
}

/// Image output format for encoding protected images.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[non_exhaustive]
pub enum ImageOutputFormat {
    /// Portable Network Graphics (default).
    #[default]
    Png,
    /// Joint Photographic Experts Group.
    Jpeg,
    /// WebP image format.
    WebP,
}

/// Default output format used when none is specified.
pub const DEFAULT_OUTPUT_FORMAT: ImageOutputFormat = ImageOutputFormat::Png;

impl ImageOutputFormat {
    /// Parses an image format from a file extension (case-insensitive).
    ///
    /// Recognizes `"png"`, `"jpg"`, `"jpeg"`, and `"webp"`.
    #[must_use]
    pub fn from_extension(ext: &str) -> Option<Self> {
        match ext.to_lowercase().as_str() {
            "png" => Some(ImageOutputFormat::Png),
            "jpg" | "jpeg" => Some(ImageOutputFormat::Jpeg),
            "webp" => Some(ImageOutputFormat::WebP),
            _ => None,
        }
    }

    /// Detects the image format from file magic bytes.
    ///
    /// Returns `None` if the bytes are too short or the format is unrecognized.
    #[must_use]
    pub fn from_magic_bytes(bytes: &[u8]) -> Option<Self> {
        if bytes.len() < 4 {
            return None;
        }
        if bytes.starts_with(&[0x89, 0x50, 0x4E, 0x47]) {
            return Some(ImageOutputFormat::Png);
        }
        if bytes.starts_with(&[0xFF, 0xD8, 0xFF]) {
            return Some(ImageOutputFormat::Jpeg);
        }
        if bytes.len() >= 12 && &bytes[0..4] == b"RIFF" && &bytes[8..12] == b"WEBP" {
            return Some(ImageOutputFormat::WebP);
        }
        None
    }

    /// Returns `true` if the bytes start with the PNG magic number.
    #[must_use]
    pub fn is_png(bytes: &[u8]) -> bool {
        bytes.len() >= 4 && bytes.starts_with(&[0x89, 0x50, 0x4E, 0x47])
    }

    /// Returns `true` if the bytes start with the JPEG magic number.
    #[must_use]
    pub fn is_jpeg(bytes: &[u8]) -> bool {
        bytes.len() >= 3 && bytes.starts_with(&[0xFF, 0xD8, 0xFF])
    }

    /// Returns `true` if the bytes start with the RIFF/WEBP magic number.
    #[must_use]
    pub fn is_webp(bytes: &[u8]) -> bool {
        bytes.len() >= 12 && &bytes[0..4] == b"RIFF" && &bytes[8..12] == b"WEBP"
    }

    /// Returns the canonical file extension for this format.
    pub fn extension(&self) -> &'static str {
        match self {
            ImageOutputFormat::Png => "png",
            ImageOutputFormat::Jpeg => "jpg",
            ImageOutputFormat::WebP => "webp",
        }
    }

    /// Converts to the corresponding `image::ImageFormat` variant.
    #[must_use]
    pub fn to_image_format(self) -> image::ImageFormat {
        match self {
            ImageOutputFormat::Png => image::ImageFormat::Png,
            ImageOutputFormat::Jpeg => image::ImageFormat::Jpeg,
            ImageOutputFormat::WebP => image::ImageFormat::WebP,
        }
    }
}
