/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Hidden-marker configuration.
 *
 * Use the static factories rather than a bare object literal: `tileSize` is
 * only meaningful for the `tiled` kind and is validated against the canonical
 * `32..=1024` range.
 */
export declare class HiddenMarkerMode {
  /** No hidden-marker work at all. */
  static disabled(): HiddenMarkerMode
  /** Minimal seed-only marker: PNG/WebP LSB seed, JPEG Q-table seed. */
  static seedOnly(): HiddenMarkerMode
  /** Non-tiled LSB/DCT hidden marker. */
  static bestEffort(): HiddenMarkerMode
  /**
   * Crop-resistant tiled hidden marker. `tileSize` must be within the
   * canonical `32..=1024` range.
   */
  static tiled(tileSize: number): HiddenMarkerMode
  /** The hidden-marker strategy. */
  get kind(): HiddenMarkerKind
  /** The tile dimension in pixels, or `null` for non-tiled modes. */
  get tileSize(): number | null
}

/** Encoding and output options applied to a protection request. */
export declare class ProcessingOptions {
  /** Creates processing options with canonical defaults. */
  constructor()
  /** Sets the encoded output format. */
  withOutputFormat(format: ImageOutputFormat): ProcessingOptions
  /** Sets the JPEG quality. */
  withJpegQuality(quality: number): ProcessingOptions
  /** Enables progressive JPEG output. */
  withProgressiveJpeg(): ProcessingOptions
  /** Sets the maximum output dimension. */
  withMaxDimension(maxDimension: number): ProcessingOptions
  /** Sets the metadata update policy. */
  withMetadataUpdatePolicy(policy: MetadataUpdatePolicy): ProcessingOptions
  /** Sets the stego redundancy override. */
  withStegoRedundancy(redundancy: number): ProcessingOptions
  /** Sets the 4-byte provenance content hash. */
  withContentHash(hash: Uint8Array): ProcessingOptions
  /** Sets the deterministic notice-applied-at timestamp override. */
  withTimestampOverride(timestamp: string): ProcessingOptions
  /** The requested output format, or `null` when unset. */
  get outputFormat(): ImageOutputFormat | null
  /** The JPEG quality. */
  get jpegQuality(): number
  /** Whether progressive JPEG output is enabled. */
  get progressiveJpeg(): boolean
  /** The maximum output dimension, or `null` when unset. */
  get maxDimension(): number | null
  /** The metadata update policy. */
  get metadataUpdatePolicy(): MetadataUpdatePolicy
  /** The stego redundancy override, or `null` when unset. */
  get stegoRedundancy(): number | null
  /** The provenance content hash bytes, or `null` when unset. */
  get contentHash(): Uint8Array | null
  /** The timestamp override, or `null` when unset. */
  get timestampOverride(): string | null
}

/**
 * The canonical protection request.
 *
 * Every protection operation delegates to `ProtectionRequest` and the
 * canonical `process_request_bytes*` byte API. Deprecated `ProtectionLevel`,
 * `ProtectionContext`, and `EvidenceProfile` adapters are intentionally not
 * projected here.
 */
export declare class ProtectionRequest {
  /** Metadata-only protection: the fastest path. */
  static metadataOnly(notice: RightsNotice, policy: RightsPolicy): ProtectionRequest
  /** Metadata plus a best-effort hidden marker. */
  static withHiddenMarker(notice: RightsNotice, policy: RightsPolicy): ProtectionRequest
  /** Protection from a named channel preset. */
  static fromPreset(preset: ProtectionPreset, notice: RightsNotice, policy: RightsPolicy): ProtectionRequest
  /**
   * Sets the steganographic seed as a full-width `bigint`.
   *
   * `0` is a valid seed. Values above `Number.MAX_SAFE_INTEGER` are
   * preserved exactly because the value never passes through a JavaScript
   * `number`.
   */
  withSeed(seed: bigint): ProtectionRequest
  /** Sets the embedding intensity in `0.0..=1.0`. */
  withIntensity(intensity: number): ProtectionRequest
  /** Sets the encoded output format. */
  withOutputFormat(format: ImageOutputFormat): ProtectionRequest
  /** Sets the JPEG quality. */
  withJpegQuality(quality: number): ProtectionRequest
  /** Enables progressive JPEG output. */
  withProgressiveJpeg(): ProtectionRequest
  /** Sets the maximum output dimension. */
  withMaxDimension(maxDimension: number): ProtectionRequest
  /** Sets the metadata update policy. */
  withMetadataUpdatePolicy(policy: MetadataUpdatePolicy): ProtectionRequest
  /** Sets the stego redundancy override (`1..=10`). */
  withStegoRedundancy(redundancy: number): ProtectionRequest
  /** Sets the 4-byte provenance content hash. */
  withContentHash(hash: Uint8Array): ProtectionRequest
  /**
   * Sets the deterministic notice-applied-at timestamp override.
   *
   * Without an override the canonical resolver uses wall-clock time, so two
   * invocations of the same request are not byte-identical.
   */
  withTimestampOverride(timestamp: string): ProtectionRequest
  /** Replaces the whole processing-options block. */
  withProcessing(processing: ProcessingOptions): ProtectionRequest
  /**
   * Sets the HMAC/MAC key. The bytes are never echoed back into reports,
   * errors, or generated declarations.
   */
  withMacKey(key: Uint8Array): ProtectionRequest
  /** Applies parser hardening limits for untrusted input. */
  withResourceLimits(limits: ResourceLimits): ProtectionRequest
  /** Replaces the hidden-marker strategy, leaving the other channels intact. */
  withHiddenMarkerMode(mode: HiddenMarkerMode): ProtectionRequest
  /** Replaces the authentication mode, leaving the other channels intact. */
  withAuthentication(mode: AuthenticationMode): ProtectionRequest
  /** Whether rights metadata is requested. */
  get rightsMetadataEnabled(): boolean
  /** The configured hidden-marker strategy. */
  get hiddenMarkerMode(): HiddenMarkerMode
  /** The configured authentication mode. */
  get authenticationMode(): AuthenticationMode
  /** The rights policy. */
  get policy(): RightsPolicy
  /** The steganographic seed as a full-width `bigint`, or `null` when unset. */
  get seed(): bigint | null
  /** The embedding intensity. */
  get intensity(): number
  /** Whether a MAC/HMAC key is configured. The key bytes are never exposed. */
  get hasMacKey(): boolean
  /** The timestamp override, or `null` when unset. */
  get timestampOverride(): string | null
}

/**
 * Parser hardening limits applied to untrusted input.
 *
 * `ResourceLimits.defaults()` returns the canonical defaults; a
 * `ResourceLimitsBuilder` derives a customized set.
 */
export declare class ResourceLimits {
  /** Returns the canonical default limits. */
  static defaults(): ResourceLimits
  /**
   * Starts a builder. Like the canonical `ResourceLimits::builder()`, the
   * new builder starts from the canonical defaults rather than from this
   * value.
   */
  toBuilder(): ResourceLimitsBuilder
  /** Maximum accepted input size in bytes. */
  get maxInputBytes(): number
  /** Maximum accepted image width in pixels. */
  get maxWidth(): number
  /** Maximum accepted image height in pixels. */
  get maxHeight(): number
  /** Maximum number of PNG chunks scanned. */
  get maxPngChunks(): number
  /** Maximum PNG chunk payload size in bytes. */
  get maxPngChunkBytes(): number
  /** Maximum number of JPEG segments scanned. */
  get maxJpegSegments(): number
  /** Maximum JPEG segment payload size in bytes. */
  get maxJpegSegmentBytes(): number
  /** Maximum number of WebP RIFF chunks scanned. */
  get maxWebpRiffChunks(): number
  /** Maximum WebP RIFF chunk payload size in bytes. */
  get maxWebpRiffBytes(): number
  /** Maximum XMP packet size in bytes. */
  get maxXmpBytes(): number
  /** Maximum XML nesting depth. */
  get maxXmlDepth(): number
  /** Maximum number of XML properties parsed. */
  get maxXmlProperties(): number
  /** Maximum number of metadata fields extracted. */
  get maxMetadataFields(): number
  /** Maximum per-field metadata size in bytes. */
  get maxMetadataFieldBytes(): number
  /** Maximum embedded payload size in bytes. */
  get maxPayloadBytes(): number
  /** Maximum detached manifest size in bytes. */
  get maxDetachedManifestBytes(): number
  /** Maximum number of tile extraction origins checked. */
  get maxTileExtractionOrigins(): number
  /** Maximum number of verification seeds tried. */
  get maxVerificationSeeds(): number
}

/**
 * Chainable builder for [`ResourceLimits`].
 *
 * The builder is immutable: every `with*` call returns a new builder, so a
 * partially configured builder can be shared safely. Limits that are never set
 * fall back to the canonical defaults.
 */
export declare class ResourceLimitsBuilder {
  /** Starts a builder seeded with the canonical default limits. */
  static new(): ResourceLimitsBuilder
  /** Sets the `maxInputBytes` limit. */
  withMaxInputBytes(value: number): ResourceLimitsBuilder
  /** Sets the `maxWidth` limit. */
  withMaxWidth(value: number): ResourceLimitsBuilder
  /** Sets the `maxHeight` limit. */
  withMaxHeight(value: number): ResourceLimitsBuilder
  /** Sets the `maxPngChunks` limit. */
  withMaxPngChunks(value: number): ResourceLimitsBuilder
  /** Sets the `maxPngChunkBytes` limit. */
  withMaxPngChunkBytes(value: number): ResourceLimitsBuilder
  /** Sets the `maxJpegSegments` limit. */
  withMaxJpegSegments(value: number): ResourceLimitsBuilder
  /** Sets the `maxJpegSegmentBytes` limit. */
  withMaxJpegSegmentBytes(value: number): ResourceLimitsBuilder
  /** Sets the `maxWebpRiffChunks` limit. */
  withMaxWebpRiffChunks(value: number): ResourceLimitsBuilder
  /** Sets the `maxWebpRiffBytes` limit. */
  withMaxWebpRiffBytes(value: number): ResourceLimitsBuilder
  /** Sets the `maxXmpBytes` limit. */
  withMaxXmpBytes(value: number): ResourceLimitsBuilder
  /** Sets the `maxXmlDepth` limit. */
  withMaxXmlDepth(value: number): ResourceLimitsBuilder
  /** Sets the `maxXmlProperties` limit. */
  withMaxXmlProperties(value: number): ResourceLimitsBuilder
  /** Sets the `maxMetadataFields` limit. */
  withMaxMetadataFields(value: number): ResourceLimitsBuilder
  /** Sets the `maxMetadataFieldBytes` limit. */
  withMaxMetadataFieldBytes(value: number): ResourceLimitsBuilder
  /** Sets the `maxPayloadBytes` limit. */
  withMaxPayloadBytes(value: number): ResourceLimitsBuilder
  /** Sets the `maxDetachedManifestBytes` limit. */
  withMaxDetachedManifestBytes(value: number): ResourceLimitsBuilder
  /** Sets the `maxTileExtractionOrigins` limit. */
  withMaxTileExtractionOrigins(value: number): ResourceLimitsBuilder
  /** Sets the `maxVerificationSeeds` limit. */
  withMaxVerificationSeeds(value: number): ResourceLimitsBuilder
  /** Builds the resource limits. */
  build(): ResourceLimits
}

/**
 * The rights/legal notice written into output metadata.
 *
 * Builders are immutable: each `with*` method returns a new notice, so a
 * partially configured notice can be shared safely.
 */
export declare class RightsNotice {
  /** Creates an empty rights notice. */
  constructor()
  /** Sets the copyright holder name. */
  withCopyrightHolder(holder: string): RightsNotice
  /** Sets the contact email for rights claims. */
  withContactEmail(email: string): RightsNotice
  /** Sets the license URL. */
  withLicenseUrl(url: string): RightsNotice
  /** Sets the usage terms text. */
  withUsageTerms(terms: string): RightsNotice
  /** Sets the creation date string. */
  withCreationDate(date: string): RightsNotice
  /** Sets the AI training constraints text. */
  withAiConstraints(constraints: string): RightsNotice
  /** Sets the web statement of rights URL. */
  withWebStatementOfRights(statement: string): RightsNotice
  /** Sets the creator name. */
  withCreator(creator: string): RightsNotice
  /** Sets the credit line. */
  withCreditLine(line: string): RightsNotice
  /** Sets the copyright owner name. */
  withCopyrightOwner(owner: string): RightsNotice
  /** Sets the licensor name. */
  withLicensorName(name: string): RightsNotice
  /** Sets the licensor email. */
  withLicensorEmail(email: string): RightsNotice
  /** Sets the licensor URL. */
  withLicensorUrl(url: string): RightsNotice
  /** Sets the metadata date string. */
  withMetadataDate(date: string): RightsNotice
  /** Sets the notice-applied-at timestamp. */
  withNoticeAppliedAt(timestamp: string): RightsNotice
  /** Sets the DMI value written alongside the notice. */
  withDmi(dmi: DmiValue): RightsNotice
  /** Sets the notice seed as a full-width `bigint`. */
  withSeed(seed: bigint): RightsNotice
  /** The copyright holder, or `null`. */
  get copyrightHolder(): string | null
  /** The contact email, or `null`. */
  get contactEmail(): string | null
  /** The license URL, or `null`. */
  get licenseUrl(): string | null
  /** The usage terms, or `null`. */
  get usageTerms(): string | null
  /** The creation date, or `null`. */
  get creationDate(): string | null
  /** The AI training constraints, or `null`. */
  get aiConstraints(): string | null
  /** The web statement of rights URL, or `null`. */
  get webStatementOfRights(): string | null
  /** The creator, or `null`. */
  get creator(): string | null
  /** The credit line, or `null`. */
  get creditLine(): string | null
  /** The copyright owner, or `null`. */
  get copyrightOwner(): string | null
  /** The licensor name, or `null`. */
  get licensorName(): string | null
  /** The licensor email, or `null`. */
  get licensorEmail(): string | null
  /** The licensor URL, or `null`. */
  get licensorUrl(): string | null
  /** The metadata date, or `null`. */
  get metadataDate(): string | null
  /** The notice-applied-at timestamp, or `null`. */
  get noticeAppliedAt(): string | null
  /** The DMI value, or `null`. */
  get dmi(): DmiValue | null
  /** The notice seed as a full-width `bigint`, or `null`. */
  get seed(): bigint | null
  /** Whether the notice carries any legal content. */
  get hasLegalContent(): boolean
}

/** Payload authentication mode for the hidden marker. */
export declare enum AuthenticationMode {
  /** CRC32 integrity only; forgeable. */
  None = 'NONE',
  /** HMAC-SHA256 authentication. */
  Hmac = 'HMAC',
}

/** HMAC authentication verification facts. */
export interface AuthenticationVerification {
  /** Whether authentication was attempted. */
  attempted: boolean
  /** HMAC status, or `null` when not applicable. */
  hmacStatus: VerificationStatus | null
  /** Authentication algorithm name. */
  algorithm: string
  /** Whether the supplied key matched the expected key. */
  keyMatched: boolean
}

/** Instance-digest and content-hash binding verification facts. */
export interface BindingVerification {
  /** Whether an instance digest was found. */
  instanceDigestPresent: boolean
  /** Whether the instance digest is valid. */
  instanceDigestValid: boolean
  /** Whether a content hash was found. */
  contentHashPresent: boolean
  /** Whether the content hash is valid. */
  contentHashValid: boolean
  /** Whether the claimed format matches the actual format. */
  formatValid: boolean
  /** Whether the claimed dimensions match the actual dimensions. */
  dimensionsValid: boolean
  /** Whether the claimed file size matches the actual file size. */
  fileSizeValid: boolean
}

/**
 * Detects the encoded image format from its magic bytes.
 *
 * This is a bounded header inspection, not a decode, so it stays synchronous
 * on the JavaScript event-loop thread. Returns the canonical lowercase
 * extension (`"png"`, `"jpg"`, `"webp"`) or `null` when unrecognized.
 */
export declare function detectFormat(data: Uint8Array): string | null

/** A verification diagnostic message. */
export interface Diagnostic {
  /** Diagnostic severity. */
  level: DiagnosticLevel
  /** Human-readable diagnostic message. */
  message: string
  /** Component that produced the diagnostic. */
  source: string
}

/** Severity of a verification diagnostic. */
export declare enum DiagnosticLevel {
  /** Informational. */
  Info = 'info',
  /** Warning. */
  Warning = 'warning',
  /** Error. */
  Error = 'error',
}

/** The DMI (Data Mining Implementation) value serialized into metadata. */
export declare enum DmiValue {
  /** No DMI restriction expressed. */
  Unspecified = 'UNSPECIFIED',
  /** DMI is allowed. */
  Allowed = 'ALLOWED',
  /** Prohibited for AI/ML training. */
  ProhibitedAiMlTraining = 'PROHIBITED_AI_ML_TRAINING',
  /** Prohibited for generative AI/ML training. */
  ProhibitedGenAiMlTraining = 'PROHIBITED_GEN_AI_ML_TRAINING',
  /** Prohibited except for search engine indexing. */
  ProhibitedExceptSearchEngineIndexing = 'PROHIBITED_EXCEPT_SEARCH_ENGINE_INDEXING',
  /** Prohibited for every use. */
  Prohibited = 'PROHIBITED',
  /** Prohibited; see the supplied constraints. */
  ProhibitedSeeConstraints = 'PROHIBITED_SEE_CONSTRAINTS',
}

/**
 * Stable machine-readable failure codes for the Node binding.
 *
 * These strings are the public `error.code` contract. They are
 * compatibility-sensitive once the first npm publication exists.
 */
export declare enum ErrorCode {
  /** Configuration or request validation failure. */
  InvalidConfig = 'ERR_STEGOEGGO_INVALID_CONFIG',
  /** The image format could not be determined or is unsupported. */
  InvalidFormat = 'ERR_STEGOEGGO_INVALID_FORMAT',
  /** Image decoding or encoding failure, including truncated input. */
  EncodeDecode = 'ERR_STEGOEGGO_ENCODE_DECODE',
  /** Metadata injection or parsing failure. */
  Metadata = 'ERR_STEGOEGGO_METADATA',
  /** Steganographic embedding or extraction failure. */
  Steganography = 'ERR_STEGOEGGO_STEGANOGRAPHY',
  /** The carrier lacks capacity for the requested payload. */
  InsufficientCapacity = 'ERR_STEGOEGGO_INSUFFICIENT_CAPACITY',
  /** Payload verification (CRC32 or HMAC) failure. */
  Verification = 'ERR_STEGOEGGO_VERIFICATION',
  /** A configured resource limit was exceeded for untrusted input. */
  ResourceLimit = 'ERR_STEGOEGGO_RESOURCE_LIMIT',
  /** Safe fallback for non-exhaustive or unexpected native failures. */
  Internal = 'ERR_STEGOEGGO_INTERNAL',
}

/** A metadata location or steganographic technique that carried evidence. */
export declare enum EvidenceChannel {
  /** PNG `tEXt`/`iTXt` text chunk. */
  PngText = 'pngText',
  /** PNG `iTXt` chunk carrying XMP. */
  PngXmp = 'pngXmp',
  /** JPEG `COM` comment marker. */
  JpegComment = 'jpegComment',
  /** JPEG `APP1` marker carrying XMP. */
  JpegXmp = 'jpegXmp',
  /** JPEG `APP13` marker carrying IPTC-IIM. */
  JpegIptc = 'jpegIptc',
  /** WebP RIFF chunk carrying XMP. */
  WebPXmp = 'webpXmp',
  /** WebP RIFF chunk carrying EXIF. */
  WebpExif = 'webpExif',
  /** LSB hidden marker in pixel data. */
  LsbPayload = 'lsbPayload',
  /** F5-style DCT hidden marker in JPEG coefficients. */
  DctPayload = 'dctPayload',
  /** Seed stored in JPEG quantization table LSBs. */
  QTableSeed = 'qTableSeed',
}

/** Combined strength of the evidence found in an image. */
export declare enum EvidenceStrength {
  /** No rights-reservation metadata was found. */
  NoNoticeFound = 'NO_NOTICE_FOUND',
  /** Metadata notice only, no verified hidden marker. */
  MetadataNoticeOnly = 'METADATA_NOTICE_ONLY',
  /** Metadata notice plus a non-authenticated hidden marker. */
  MetadataNoticeAndBestEffortStego = 'METADATA_NOTICE_AND_BEST_EFFORT_STEGO',
  /** Metadata notice plus an authenticated hidden marker. */
  MetadataNoticeAndAuthenticatedProvenance = 'METADATA_NOTICE_AND_AUTHENTICATED_PROVENANCE',
}

/** Which channels ran, which degraded, and what the effective policy was. */
export interface ExecutionReport {
  /** Effective rights policy after resolution. */
  effectivePolicy: RightsPolicy
  /** DMI value serialized into metadata, or `null`. */
  effectiveDmi: DmiValue | null
  /** Whether rights metadata was injected. */
  metadataInjected: boolean
  /** Whether hidden-marker embedding was attempted. */
  stegoAttempted: boolean
  /** Whether hidden-marker embedding succeeded. */
  stegoSucceeded: boolean
  /** Whether the output format differs from the input format. */
  formatTranscoded: boolean
  /** Degradation and advisory conditions raised during protection. */
  warnings: Array<ProtectionWarning>
  /** Whether any requested channel executed successfully. */
  anySucceeded: boolean
  /** Whether any requested channel was degraded or skipped. */
  hasDegradation: boolean
  /** Observed resource usage, or `null` when untracked. */
  resourceUsage: ResourceUsage | null
}

/** Where a verification fact was read from. */
export declare enum FieldSource {
  /** Extracted from XMP metadata. */
  Xmp = 'xmp',
  /** Extracted from legacy non-XMP metadata. */
  Legacy = 'legacy',
  /** Extracted from an embedded V1 payload. */
  EmbeddedPayloadV1 = 'embeddedPayloadV1',
  /** Extracted from an embedded V2 payload. */
  EmbeddedPayloadV2 = 'embeddedPayloadV2',
  /** Extracted from an embedded V3 payload. */
  EmbeddedPayloadV3 = 'embeddedPayloadV3',
  /** Extracted from a detached manifest. */
  DetachedManifest = 'detachedManifest',
  /** Extracted from JPEG quantization table seed bits. */
  QTableSeed = 'qTableSeed',
}

/** The hidden-marker strategy discriminator. */
export declare enum HiddenMarkerKind {
  /** No hidden marker work at all. */
  Disabled = 'disabled',
  /** Minimal seed-only marker (PNG/WebP LSB seed, JPEG Q-table seed). */
  SeedOnly = 'seedOnly',
  /** Non-tiled LSB/DCT hidden marker. */
  BestEffort = 'bestEffort',
  /** Crop-resistant tiled hidden marker. */
  Tiled = 'tiled',
}

/** Hidden steganographic marker verification facts. */
export interface HiddenMarkerVerification {
  /** Status of the hidden marker. */
  status: VerificationStatus
  /** Detected payload version, or `null`. */
  payloadVersion: number | null
  /** Extracted seed as a full-width `bigint`, or `null`. */
  seed: bigint | null
  /** Extracted embedding intensity, or `null`. */
  intensity: number | null
  /** Whether tiled steganography was detected. */
  tiled: boolean
  /** Where the marker was read from. */
  source: FieldSource
}

/** The encoded output container format. */
export declare enum ImageOutputFormat {
  /** Portable Network Graphics. */
  Png = 'PNG',
  /** Joint Photographic Experts Group. */
  Jpeg = 'JPEG',
  /** WebP image format. */
  WebP = 'WEBP',
}

/** How existing StegoEggo-owned metadata is treated on write. */
export declare enum MetadataUpdatePolicy {
  /** Replace StegoEggo-owned properties, preserve unrelated metadata. */
  ReplaceStegoOwned = 'REPLACE_STEGO_OWNED',
  /** Fail when conflicting StegoEggo metadata already exists. */
  FailOnConflict = 'FAIL_ON_CONFLICT',
  /** Preserve existing StegoEggo metadata and only add new fields. */
  PreserveExisting = 'PRESERVE_EXISTING',
}

/**
 * Structured native error payload projected out of a canonical Rust failure.
 *
 * The public JavaScript error is built from this DTO by the package's thin
 * wrapper so that `code` and the structured fields survive Promise rejection.
 * Field values are `null` when the canonical variant does not carry them.
 */
export interface NativeError {
  /** Stable machine-readable code. */
  code: ErrorCode
  /** Human-readable description. Never the machine contract. */
  message: string
  /** Resource category for limit failures. */
  resource: string | null
  /** Required carrier units for `ERR_STEGOEGGO_INSUFFICIENT_CAPACITY`. */
  required: number | null
  /** Available carrier units for `ERR_STEGOEGGO_INSUFFICIENT_CAPACITY`. */
  available: number | null
  /** Observed size for `input_bytes` and `metadata` limit failures. */
  size: number | null
  /** Configured limit for limit failures. */
  limit: number | null
  /** Observed image width for `dimensions` limit failures. */
  width: number | null
  /** Observed image height for `dimensions` limit failures. */
  height: number | null
  /** Configured maximum width for `dimensions` limit failures. */
  maxWidth: number | null
  /** Configured maximum height for `dimensions` limit failures. */
  maxHeight: number | null
  /** Container or budget kind for `container` and `verification_budget`. */
  kind: string | null
  /** Observed count for `container` and `verification_budget` failures. */
  count: number | null
}

/**
 * Native entry point behind the public `protect` Promise. Copies the
 * JavaScript bytes into Rust-owned storage before scheduling the worker.
 */
export declare function protectInternal(data: Uint8Array, request: ProtectionRequest): Promise<ProtectOutcome>

/** A named bundle of protection channels. */
export declare enum ProtectionPreset {
  /** Metadata notice only. No hidden marker, no MAC. */
  LegalNotice = 'LEGAL_NOTICE',
  /** Metadata notice plus best-effort hidden marker. */
  LegalNoticeWithStego = 'LEGAL_NOTICE_WITH_STEGO',
  /** Metadata plus hidden marker plus HMAC authentication. */
  AuthenticatedProvenance = 'AUTHENTICATED_PROVENANCE',
  /** Every available channel. Requires a MAC key. */
  Maximal = 'MAXIMAL',
}

/** A degradation or advisory condition raised during protection. */
export declare enum ProtectionWarning {
  /** No MAC key was configured; integrity is CRC32-only and forgeable. */
  MissingMacKey = 'MISSING_MAC_KEY',
  /** Metadata injection was disabled. */
  MetadataInjectionDisabled = 'METADATA_INJECTION_DISABLED',
  /** Progressive JPEG fell back to Q-table seed only. */
  ProgressiveJpegFallback = 'PROGRESSIVE_JPEG_FALLBACK',
  /** JPEG output is fragile under downstream re-encoding. */
  JpegReencodeFragile = 'JPEG_REENCODE_FRAGILE',
  /** Image too small for LSB hidden-marker embedding. */
  LsbCapacitySkipped = 'LSB_CAPACITY_SKIPPED',
  /** JPEG DCT coefficients insufficient for full embedding. */
  DctCapacityInsufficient = 'DCT_CAPACITY_INSUFFICIENT',
  /** Legal claims disabled while legal metadata is present. */
  ContradictoryLegalClaims = 'CONTRADICTORY_LEGAL_CLAIMS',
  /** `PROHIBITED_SEE_CONSTRAINTS` selected without constraints. */
  MissingRightsConstraints = 'MISSING_RIGHTS_CONSTRAINTS',
}

/** Result of a `protect` call: the protected bytes, or a structured failure. */
export interface ProtectOutcome {
  /** Protected encoded bytes, or `null` on failure. */
  data: Buffer | null
  /** Structured failure, or `null` on success. */
  error: NativeError | null
}

/** Native entry point behind the public `protectWithReport` Promise. */
export declare function protectWithReportInternal(data: Uint8Array, request: ProtectionRequest): Promise<ProtectWithReportOutcome>

/** Result of a `protectWithReport` call. */
export interface ProtectWithReportOutcome {
  /** Protected encoded bytes, or `null` on failure. */
  data: Buffer | null
  /** Execution report, or `null` on failure. */
  report: ExecutionReport | null
  /** Structured failure, or `null` on success. */
  error: NativeError | null
}

/** Native entry point behind the public `protectWithWarnings` Promise. */
export declare function protectWithWarningsInternal(data: Uint8Array, request: ProtectionRequest): Promise<ProtectWithWarningsOutcome>

/** Result of a `protectWithWarnings` call. */
export interface ProtectWithWarningsOutcome {
  /** Protected encoded bytes, or `null` on failure. */
  data: Buffer | null
  /** Degradation and advisory conditions, or `null` on failure. */
  warnings: Array<ProtectionWarning> | null
  /** Structured failure, or `null` on success. */
  error: NativeError | null
}

/** Observed resource usage for a single operation. */
export interface ResourceUsage {
  /** Total input bytes processed. */
  inputBytes: number
  /** Number of PNG chunks scanned. */
  pngChunksScanned: number
  /** Number of JPEG segments scanned. */
  jpegSegmentsScanned: number
  /** Number of WebP RIFF chunks scanned. */
  webpRiffChunksScanned: number
  /** Total XMP bytes parsed. */
  xmpBytesParsed: number
  /** Number of metadata fields extracted. */
  metadataFieldsExtracted: number
  /** Total metadata bytes copied. */
  metadataBytesCopied: number
  /** Number of tile origins checked during extraction. */
  tileOriginsChecked: number
  /** Number of verification seeds tried. */
  verificationSeedsTried: number
  /** Largest single allocation observed. */
  peakAllocationsBytes: number
}

/**
 * The rights policy written into the output metadata.
 *
 * This is the canonical `RightsPolicy` domain model; it is never inferred
 * from intensity, format, or channel selection.
 */
export declare enum RightsPolicy {
  /** No restriction expressed. */
  Unspecified = 'UNSPECIFIED',
  /** Use is allowed. */
  Allowed = 'ALLOWED',
  /** Prohibited for AI/ML training. */
  ProhibitedAiMlTraining = 'PROHIBITED_AI_ML_TRAINING',
  /** Prohibited for generative AI training. */
  ProhibitedGenerativeAiTraining = 'PROHIBITED_GENERATIVE_AI_TRAINING',
  /** Prohibited except for search indexing. */
  ProhibitedExceptSearchIndexing = 'PROHIBITED_EXCEPT_SEARCH_INDEXING',
  /** All data mining prohibited. */
  ProhibitedAllDataMining = 'PROHIBITED_ALL_DATA_MINING',
  /** Prohibited; see the supplied constraints. */
  ProhibitedSeeConstraints = 'PROHIBITED_SEE_CONSTRAINTS',
}

/** Rights and legal-notice verification facts. */
export interface RightsVerification {
  /** Whether any rights notice was found. */
  found: boolean
  /** Detected copyright holder, or `null`. */
  copyrightHolder: string | null
  /** Detected creator, or `null`. */
  creator: string | null
  /** Detected contact, or `null`. */
  contact: string | null
  /** Detected rights URL, or `null`. */
  rightsUrl: string | null
  /** Detected license URL, or `null`. */
  licenseUrl: string | null
  /** Detected usage terms, or `null`. */
  usageTerms: string | null
  /** Detected AI training constraints, or `null`. */
  aiConstraints: string | null
  /** Detected DMI byte value, or `null`. */
  dmi: number | null
  /** Where the notice was read from. */
  source: FieldSource
  /** Metadata locations that carried evidence. */
  channels: Array<EvidenceChannel>
}

/** The wrapped StegoEggo library version, identical to the package version. */
export declare function stegoeggoVersion(): string

/** Trust evaluation of the discovered evidence. */
export interface TrustEvaluation {
  /** Trust model name. */
  trustModel: string
  /** Whether the evidence is trusted. */
  trusted: boolean
  /** Human-readable trust reason. */
  reason: string
}

/** The canonical structured verification report. */
export interface VerificationReport {
  /** Summary status across all channels. */
  status: VerificationStatus
  /** Combined strength of the discovered evidence. */
  evidenceStrength: EvidenceStrength
  /** Whether any error-level diagnostic or failure was recorded. */
  hasErrors: boolean
  /** Rights and legal-notice facts. */
  rights: RightsVerification
  /** Hidden-marker facts. */
  hiddenMarker: HiddenMarkerVerification
  /** HMAC authentication facts. */
  authentication: AuthenticationVerification
  /** Instance-digest and content-hash binding facts. */
  bindings: BindingVerification
  /** Trust evaluation of the discovered evidence. */
  trust: TrustEvaluation
  /** Diagnostics produced during verification. */
  diagnostics: Array<Diagnostic>
}

/** Coarse verification status for the hidden marker. */
export declare enum VerificationStatus {
  /** Payload extracted and verified. */
  Verified = 'VERIFIED',
  /** Payload found but failed verification. */
  Invalid = 'INVALID',
  /** No payload found. */
  NotFound = 'NOT_FOUND',
}

/** Native entry point behind the public `verify` Promise. */
export declare function verifyInternal(data: Uint8Array, macKey?: Uint8Array | undefined | null, resourceLimits?: ResourceLimits | undefined | null): Promise<VerifyOutcome>

/** Result of a `verify` call. */
export interface VerifyOutcome {
  /** Canonical verification report, or `null` on failure. */
  report: VerificationReport | null
  /** Structured failure, or `null` on success. */
  error: NativeError | null
}
