'use strict'

/**
 * Public Node entry point for the StegoEggo napi-rs binding.
 *
 * The native module (`./index.js`, generated by `@napi-rs/cli`) resolves and
 * loads the platform `.node` addon and owns every value and type projected from
 * the canonical Rust API. This wrapper is the only hand-written runtime layer:
 * it turns the native operation outcomes into Promise-based public operations
 * whose failures reject with a real `Error` carrying the stable `code` and the
 * structured fields, because `AsyncTask::reject` cannot attach properties.
 *
 * Nothing here re-implements protection logic. Every operation delegates to
 * `process_request_bytes*` or `verify_image_bytes_report` in Rust.
 */

const native = require('./index.js')

/** Every structured field a binding failure can carry, in stable order. */
const STRUCTURED_FIELDS = [
  'resource',
  'required',
  'available',
  'size',
  'limit',
  'width',
  'height',
  'maxWidth',
  'maxHeight',
  'kind',
  'count',
]

/**
 * Maps a native throw onto the stable `ERR_STEGOEGGO_*` family.
 *
 * napi-rs raises its own Node-API statuses (argument conversion, worker
 * scheduling) before this binding's own codes exist. Those are configuration
 * or internal problems, never a domain failure, and must not escape as raw
 * Node-API status strings.
 *
 * @param {unknown} code the thrown error's `code`
 * @returns {string} a stable binding code
 */
function normalizeNativeCode (code) {
  if (typeof code === 'string' && code.startsWith('ERR_STEGOEGGO_')) {
    return code
  }
  if (code === 'InvalidArg' || code === 'ERR_INVALID_ARG_TYPE') {
    return 'ERR_STEGOEGGO_INVALID_CONFIG'
  }
  return 'ERR_STEGOEGGO_INTERNAL'
}

/**
 * Builds the public `Error` for a native failure DTO.
 *
 * @param {object} dto native `NativeError`
 * @returns {Error} a normal `Error` with `code` and structured fields
 */
function toPublicError (dto) {
  const error = new Error(
    typeof dto?.message === 'string' ? dto.message : 'stegoeggo operation failed'
  )
  error.name = 'StegoEggoError'
  error.code = normalizeNativeCode(dto?.code)
  for (const field of STRUCTURED_FIELDS) {
    if (dto && dto[field] !== null && dto[field] !== undefined) {
      error[field] = dto[field]
    }
  }
  return error
}

/**
 * Normalizes an outcome that carries `data`/`warnings`/`report` or `error`.
 *
 * @param {object} outcome native operation outcome
 * @returns {object} the successful payload
 */
function unwrap (outcome) {
  if (outcome && outcome.error) {
    throw toPublicError(outcome.error)
  }
  return outcome
}

/**
 * Runs a native operation and converts any synchronous native throw into the
 * same structured-error contract, so callers only ever see rejections.
 *
 * @param {() => Promise<object>} operation native call
 * @returns {Promise<object>} the successful payload
 */
async function settle (operation) {
  let outcome
  try {
    outcome = await operation()
  } catch (nativeError) {
    throw toPublicError({
      code: nativeError?.code,
      message: nativeError?.message ?? String(nativeError),
    })
  }
  return unwrap(outcome)
}

/**
 * Protects encoded image bytes with the canonical request.
 *
 * Runs on a libuv worker thread, so the JavaScript event loop stays free.
 * The input bytes are copied into Rust-owned storage before the worker starts.
 *
 * @param {Buffer|Uint8Array} data encoded PNG/JPEG/WebP bytes
 * @param {import('./index.js').ProtectionRequest} request canonical request
 * @returns {Promise<Buffer>} protected encoded bytes
 */
async function protect (data, request) {
  const outcome = await settle(() => native.protectInternal(data, request))
  return outcome.data
}

/**
 * Protects encoded image bytes and returns the degradation warnings.
 *
 * @param {Buffer|Uint8Array} data encoded PNG/JPEG/WebP bytes
 * @param {import('./index.js').ProtectionRequest} request canonical request
 * @returns {Promise<{ data: Buffer, warnings: string[] }>} protected bytes and warnings
 */
async function protectWithWarnings (data, request) {
  const outcome = await settle(() => native.protectWithWarningsInternal(data, request))
  return { data: outcome.data, warnings: outcome.warnings }
}

/**
 * Protects encoded image bytes and returns the execution report.
 *
 * @param {Buffer|Uint8Array} data encoded PNG/JPEG/WebP bytes
 * @param {import('./index.js').ProtectionRequest} request canonical request
 * @returns {Promise<{ data: Buffer, report: import('./index.js').ExecutionReport }>} output and report
 */
async function protectWithReport (data, request) {
  const outcome = await settle(() => native.protectWithReportInternal(data, request))
  return { data: outcome.data, report: outcome.report }
}

/**
 * Verifies encoded image bytes.
 *
 * Runs on a libuv worker thread. Never rejects for a missing or invalid
 * marker: read `report.status` and `report.evidenceStrength` instead.
 *
 * @param {Buffer|Uint8Array} data encoded PNG/JPEG/WebP bytes
 * @param {{ macKey?: Buffer|Uint8Array, resourceLimits?: import('./index.js').ResourceLimits }} [options]
 * @returns {Promise<import('./index.js').VerificationReport>} canonical report
 */
async function verify (data, options) {
  const outcome = await settle(() =>
    native.verifyInternal(data, options?.macKey, options?.resourceLimits)
  )
  return outcome.report
}

module.exports = {
  ...native,
  protect,
  protectWithWarnings,
  protectWithReport,
  verify,
  toPublicError,
}
