#ifndef stegoeggo
#define stegoeggo

/* Generated by cbindgen 0.29.4. Do not edit. Regenerate with bindings/c/scripts/generate-header.sh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define STEGOEGGO_V1_ABI_MAJOR 1

#define STEGOEGGO_V1_ABI_MINOR 0

#define STEGOEGGO_V1_AUTH_HMAC 1

#define STEGOEGGO_V1_AUTH_NONE 0

#define STEGOEGGO_V1_DMI_ALLOWED 1

#define STEGOEGGO_V1_DMI_PROHIBITED 5

#define STEGOEGGO_V1_DMI_PROHIBITED_AI_ML_TRAINING 2

#define STEGOEGGO_V1_DMI_PROHIBITED_EXCEPT_SEARCH_ENGINE_INDEXING 4

#define STEGOEGGO_V1_DMI_PROHIBITED_GEN_AI_ML_TRAINING 3

#define STEGOEGGO_V1_DMI_PROHIBITED_SEE_CONSTRAINTS 6

#define STEGOEGGO_V1_DMI_UNSPECIFIED 0

#define STEGOEGGO_V1_ERR_ENCODE_DECODE 4

#define STEGOEGGO_V1_ERR_INSUFFICIENT_CAPACITY 7

#define STEGOEGGO_V1_ERR_INTERNAL 10

#define STEGOEGGO_V1_ERR_INVALID_ARGUMENT 1

#define STEGOEGGO_V1_ERR_INVALID_CONFIGURATION 2

#define STEGOEGGO_V1_ERR_INVALID_FORMAT 3

#define STEGOEGGO_V1_ERR_METADATA 5

#define STEGOEGGO_V1_ERR_RESOURCE_LIMIT 9

#define STEGOEGGO_V1_ERR_STEGANOGRAPHY 6

#define STEGOEGGO_V1_ERR_VERIFICATION 8

#define STEGOEGGO_V1_EVIDENCE_METADATA_NOTICE_AND_AUTHENTICATED_PROVENANCE 3

#define STEGOEGGO_V1_EVIDENCE_METADATA_NOTICE_AND_BEST_EFFORT_STEGO 2

#define STEGOEGGO_V1_EVIDENCE_METADATA_NOTICE_ONLY 1

#define STEGOEGGO_V1_EVIDENCE_NO_NOTICE_FOUND 0

#define STEGOEGGO_V1_FORMAT_JPEG 2

#define STEGOEGGO_V1_FORMAT_PNG 1

#define STEGOEGGO_V1_FORMAT_UNKNOWN 0

#define STEGOEGGO_V1_FORMAT_WEBP 3

#define STEGOEGGO_V1_MARKER_BEST_EFFORT 2

#define STEGOEGGO_V1_MARKER_DISABLED 0

#define STEGOEGGO_V1_MARKER_SEED_ONLY 1

#define STEGOEGGO_V1_MARKER_TILED 3

#define STEGOEGGO_V1_OK 0

#define STEGOEGGO_V1_POLICY_ALLOWED 1

#define STEGOEGGO_V1_POLICY_PROHIBITED_AI_ML_TRAINING 2

#define STEGOEGGO_V1_POLICY_PROHIBITED_ALL_DATA_MINING 5

#define STEGOEGGO_V1_POLICY_PROHIBITED_EXCEPT_SEARCH_INDEXING 4

#define STEGOEGGO_V1_POLICY_PROHIBITED_GENERATIVE_AI_TRAINING 3

#define STEGOEGGO_V1_POLICY_PROHIBITED_SEE_CONSTRAINTS 6

#define STEGOEGGO_V1_POLICY_UNSPECIFIED 0

#define STEGOEGGO_V1_PRESET_AUTHENTICATED_PROVENANCE 2

#define STEGOEGGO_V1_PRESET_LEGAL_NOTICE 0

#define STEGOEGGO_V1_PRESET_LEGAL_NOTICE_WITH_STEGO 1

#define STEGOEGGO_V1_PRESET_MAXIMAL 3

#define STEGOEGGO_V1_RESOURCE_CARRIER 6

#define STEGOEGGO_V1_RESOURCE_CONTAINER 3

#define STEGOEGGO_V1_RESOURCE_DIMENSIONS 2

#define STEGOEGGO_V1_RESOURCE_INPUT_BYTES 1

#define STEGOEGGO_V1_RESOURCE_METADATA 4

#define STEGOEGGO_V1_RESOURCE_NONE 0

#define STEGOEGGO_V1_RESOURCE_VERIFICATION_BUDGET 5

#define STEGOEGGO_V1_UPDATE_FAIL_ON_CONFLICT 1

#define STEGOEGGO_V1_UPDATE_PRESERVE_EXISTING 2

#define STEGOEGGO_V1_UPDATE_REPLACE_STEGO_OWNED 0

#define STEGOEGGO_V1_VERIFY_INVALID 1

#define STEGOEGGO_V1_VERIFY_NOT_FOUND 2

#define STEGOEGGO_V1_VERIFY_VERIFIED 0

#define STEGOEGGO_V1_WARNING_CONTRADICTORY_LEGAL_CLAIMS 6

#define STEGOEGGO_V1_WARNING_DCT_CAPACITY_INSUFFICIENT 5

#define STEGOEGGO_V1_WARNING_JPEG_REENCODE_FRAGILE 3

#define STEGOEGGO_V1_WARNING_LSB_CAPACITY_SKIPPED 4

#define STEGOEGGO_V1_WARNING_METADATA_INJECTION_DISABLED 1

#define STEGOEGGO_V1_WARNING_MISSING_MAC_KEY 0

#define STEGOEGGO_V1_WARNING_MISSING_RIGHTS_CONSTRAINTS 7

#define STEGOEGGO_V1_WARNING_PROGRESSIVE_JPEG_FALLBACK 2

typedef struct stegoeggo_v1_buffer_t stegoeggo_v1_buffer_t;

typedef struct stegoeggo_v1_error_t stegoeggo_v1_error_t;

typedef struct stegoeggo_v1_execution_report_t stegoeggo_v1_execution_report_t;

typedef struct stegoeggo_v1_notice_t stegoeggo_v1_notice_t;

typedef struct stegoeggo_v1_request_t stegoeggo_v1_request_t;

typedef struct stegoeggo_v1_resource_limits_t stegoeggo_v1_resource_limits_t;

typedef struct stegoeggo_v1_verification_report_t stegoeggo_v1_verification_report_t;

typedef uint32_t stegoeggo_v1_status_t;

typedef uint32_t stegoeggo_v1_image_format_t;

typedef uint32_t stegoeggo_v1_error_code_t;

typedef uint32_t stegoeggo_v1_resource_code_t;

typedef uint32_t stegoeggo_v1_dmi_value_t;

typedef uint32_t stegoeggo_v1_rights_policy_t;

typedef uint32_t stegoeggo_v1_warning_t;

typedef uint32_t stegoeggo_v1_preset_t;

typedef uint32_t stegoeggo_v1_authentication_mode_t;

typedef uint32_t stegoeggo_v1_hidden_marker_mode_t;

typedef uint32_t stegoeggo_v1_metadata_update_policy_t;

typedef uint32_t stegoeggo_v1_evidence_strength_t;

typedef uint32_t stegoeggo_v1_verification_status_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint32_t stegoeggo_abi_version_major(void);

uint32_t stegoeggo_abi_version_minor(void);

const char *stegoeggo_source_version(void);

const uint8_t *stegoeggo_v1_buffer_data(const struct stegoeggo_v1_buffer_t *buffer);

void stegoeggo_v1_buffer_free(struct stegoeggo_v1_buffer_t *buffer);

size_t stegoeggo_v1_buffer_len(const struct stegoeggo_v1_buffer_t *buffer);

stegoeggo_v1_status_t stegoeggo_v1_detect_format(const uint8_t *data,
                                                 size_t data_len,
                                                 stegoeggo_v1_image_format_t *out_format,
                                                 struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_error_code_t stegoeggo_v1_error_code(const struct stegoeggo_v1_error_t *error);

struct stegoeggo_v1_buffer_t *stegoeggo_v1_error_details_json(const struct stegoeggo_v1_error_t *error);

void stegoeggo_v1_error_free(struct stegoeggo_v1_error_t *error);

const char *stegoeggo_v1_error_message_data(const struct stegoeggo_v1_error_t *error);

size_t stegoeggo_v1_error_message_len(const struct stegoeggo_v1_error_t *error);

stegoeggo_v1_resource_code_t stegoeggo_v1_error_resource(const struct stegoeggo_v1_error_t *error);

stegoeggo_v1_dmi_value_t stegoeggo_v1_execution_report_effective_dmi(const struct stegoeggo_v1_execution_report_t *report);

stegoeggo_v1_rights_policy_t stegoeggo_v1_execution_report_effective_policy(const struct stegoeggo_v1_execution_report_t *report);

uint8_t stegoeggo_v1_execution_report_format_transcoded(const struct stegoeggo_v1_execution_report_t *report);

void stegoeggo_v1_execution_report_free(struct stegoeggo_v1_execution_report_t *report);

uint8_t stegoeggo_v1_execution_report_has_dmi(const struct stegoeggo_v1_execution_report_t *report);

uint8_t stegoeggo_v1_execution_report_metadata_injected(const struct stegoeggo_v1_execution_report_t *report);

uint8_t stegoeggo_v1_execution_report_stego_attempted(const struct stegoeggo_v1_execution_report_t *report);

uint8_t stegoeggo_v1_execution_report_stego_succeeded(const struct stegoeggo_v1_execution_report_t *report);

stegoeggo_v1_warning_t stegoeggo_v1_execution_report_warning_at(const struct stegoeggo_v1_execution_report_t *report,
                                                                size_t index);

size_t stegoeggo_v1_execution_report_warning_count(const struct stegoeggo_v1_execution_report_t *report);

stegoeggo_v1_status_t stegoeggo_v1_notice_create(struct stegoeggo_v1_notice_t **out_notice,
                                                 struct stegoeggo_v1_error_t **out_error);

void stegoeggo_v1_notice_free(struct stegoeggo_v1_notice_t *notice);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_ai_constraints(struct stegoeggo_v1_notice_t *notice,
                                                             const char *text,
                                                             size_t text_len,
                                                             struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_contact_email(struct stegoeggo_v1_notice_t *notice,
                                                            const char *text,
                                                            size_t text_len,
                                                            struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_copyright_holder(struct stegoeggo_v1_notice_t *notice,
                                                               const char *text,
                                                               size_t text_len,
                                                               struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_copyright_owner(struct stegoeggo_v1_notice_t *notice,
                                                              const char *text,
                                                              size_t text_len,
                                                              struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_creation_date(struct stegoeggo_v1_notice_t *notice,
                                                            const char *text,
                                                            size_t text_len,
                                                            struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_creator(struct stegoeggo_v1_notice_t *notice,
                                                      const char *text,
                                                      size_t text_len,
                                                      struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_credit_line(struct stegoeggo_v1_notice_t *notice,
                                                          const char *text,
                                                          size_t text_len,
                                                          struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_dmi(struct stegoeggo_v1_notice_t *notice,
                                                  stegoeggo_v1_dmi_value_t dmi,
                                                  struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_license_url(struct stegoeggo_v1_notice_t *notice,
                                                          const char *text,
                                                          size_t text_len,
                                                          struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_licensor_email(struct stegoeggo_v1_notice_t *notice,
                                                             const char *text,
                                                             size_t text_len,
                                                             struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_licensor_name(struct stegoeggo_v1_notice_t *notice,
                                                            const char *text,
                                                            size_t text_len,
                                                            struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_licensor_url(struct stegoeggo_v1_notice_t *notice,
                                                           const char *text,
                                                           size_t text_len,
                                                           struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_metadata_date(struct stegoeggo_v1_notice_t *notice,
                                                            const char *text,
                                                            size_t text_len,
                                                            struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_notice_applied_at(struct stegoeggo_v1_notice_t *notice,
                                                                const char *text,
                                                                size_t text_len,
                                                                struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_seed(struct stegoeggo_v1_notice_t *notice,
                                                   uint8_t has_seed,
                                                   uint64_t seed,
                                                   struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_usage_terms(struct stegoeggo_v1_notice_t *notice,
                                                          const char *text,
                                                          size_t text_len,
                                                          struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_usage_terms_lang(struct stegoeggo_v1_notice_t *notice,
                                                               const char *text,
                                                               size_t text_len,
                                                               struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_notice_set_web_statement_of_rights(struct stegoeggo_v1_notice_t *notice,
                                                                      const char *text,
                                                                      size_t text_len,
                                                                      struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_protect(const uint8_t *data,
                                           size_t data_len,
                                           const struct stegoeggo_v1_request_t *request,
                                           struct stegoeggo_v1_buffer_t **out_data,
                                           struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_protect_with_report(const uint8_t *data,
                                                       size_t data_len,
                                                       const struct stegoeggo_v1_request_t *request,
                                                       struct stegoeggo_v1_buffer_t **out_data,
                                                       struct stegoeggo_v1_execution_report_t **out_report,
                                                       struct stegoeggo_v1_error_t **out_error);

void stegoeggo_v1_request_free(struct stegoeggo_v1_request_t *request);

stegoeggo_v1_status_t stegoeggo_v1_request_from_preset(stegoeggo_v1_preset_t preset,
                                                       const struct stegoeggo_v1_notice_t *notice,
                                                       stegoeggo_v1_rights_policy_t policy,
                                                       struct stegoeggo_v1_request_t **out_request,
                                                       struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_metadata_only(const struct stegoeggo_v1_notice_t *notice,
                                                         stegoeggo_v1_rights_policy_t policy,
                                                         struct stegoeggo_v1_request_t **out_request,
                                                         struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_authentication_mode(struct stegoeggo_v1_request_t *request,
                                                                   stegoeggo_v1_authentication_mode_t mode,
                                                                   struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_content_hash(struct stegoeggo_v1_request_t *request,
                                                            uint8_t has_hash,
                                                            const uint8_t *hash,
                                                            size_t hash_len,
                                                            struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_hidden_marker_mode(struct stegoeggo_v1_request_t *request,
                                                                  stegoeggo_v1_hidden_marker_mode_t mode,
                                                                  uint32_t tile_size,
                                                                  struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_intensity(struct stegoeggo_v1_request_t *request,
                                                         float intensity,
                                                         struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_jpeg_quality(struct stegoeggo_v1_request_t *request,
                                                            uint8_t quality,
                                                            struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_mac_key(struct stegoeggo_v1_request_t *request,
                                                       const uint8_t *key,
                                                       size_t key_len,
                                                       struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_max_dimension(struct stegoeggo_v1_request_t *request,
                                                             uint8_t has_max,
                                                             uint32_t max_dimension,
                                                             struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_metadata_update_policy(struct stegoeggo_v1_request_t *request,
                                                                      stegoeggo_v1_metadata_update_policy_t policy,
                                                                      struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_output_format(struct stegoeggo_v1_request_t *request,
                                                             uint8_t has_format,
                                                             stegoeggo_v1_image_format_t format,
                                                             struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_progressive_jpeg(struct stegoeggo_v1_request_t *request,
                                                                uint8_t enabled,
                                                                struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_resource_limits(struct stegoeggo_v1_request_t *request,
                                                               const struct stegoeggo_v1_resource_limits_t *limits,
                                                               struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_seed(struct stegoeggo_v1_request_t *request,
                                                    uint8_t has_seed,
                                                    uint64_t seed,
                                                    struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_stego_redundancy(struct stegoeggo_v1_request_t *request,
                                                                uint8_t has_redundancy,
                                                                uint32_t redundancy,
                                                                struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_set_timestamp_override(struct stegoeggo_v1_request_t *request,
                                                                  uint8_t has_ts,
                                                                  const char *text,
                                                                  size_t text_len,
                                                                  struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_request_with_hidden_marker(const struct stegoeggo_v1_notice_t *notice,
                                                              stegoeggo_v1_rights_policy_t policy,
                                                              struct stegoeggo_v1_request_t **out_request,
                                                              struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_create(struct stegoeggo_v1_resource_limits_t **out_limits,
                                                          struct stegoeggo_v1_error_t **out_error);

void stegoeggo_v1_resource_limits_free(struct stegoeggo_v1_resource_limits_t *limits);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_detached_manifest_bytes(struct stegoeggo_v1_resource_limits_t *limits,
                                                                                   size_t value,
                                                                                   struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_height(struct stegoeggo_v1_resource_limits_t *limits,
                                                                  uint32_t value,
                                                                  struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_input_bytes(struct stegoeggo_v1_resource_limits_t *limits,
                                                                       size_t value,
                                                                       struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_jpeg_segment_bytes(struct stegoeggo_v1_resource_limits_t *limits,
                                                                              size_t value,
                                                                              struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_jpeg_segments(struct stegoeggo_v1_resource_limits_t *limits,
                                                                         size_t value,
                                                                         struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_metadata_field_bytes(struct stegoeggo_v1_resource_limits_t *limits,
                                                                                size_t value,
                                                                                struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_metadata_fields(struct stegoeggo_v1_resource_limits_t *limits,
                                                                           size_t value,
                                                                           struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_payload_bytes(struct stegoeggo_v1_resource_limits_t *limits,
                                                                         size_t value,
                                                                         struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_png_chunk_bytes(struct stegoeggo_v1_resource_limits_t *limits,
                                                                           size_t value,
                                                                           struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_png_chunks(struct stegoeggo_v1_resource_limits_t *limits,
                                                                      size_t value,
                                                                      struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_tile_extraction_origins(struct stegoeggo_v1_resource_limits_t *limits,
                                                                                   size_t value,
                                                                                   struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_verification_seeds(struct stegoeggo_v1_resource_limits_t *limits,
                                                                              size_t value,
                                                                              struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_webp_riff_bytes(struct stegoeggo_v1_resource_limits_t *limits,
                                                                           size_t value,
                                                                           struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_webp_riff_chunks(struct stegoeggo_v1_resource_limits_t *limits,
                                                                            size_t value,
                                                                            struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_width(struct stegoeggo_v1_resource_limits_t *limits,
                                                                 uint32_t value,
                                                                 struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_xml_depth(struct stegoeggo_v1_resource_limits_t *limits,
                                                                     size_t value,
                                                                     struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_xml_properties(struct stegoeggo_v1_resource_limits_t *limits,
                                                                          size_t value,
                                                                          struct stegoeggo_v1_error_t **out_error);

stegoeggo_v1_status_t stegoeggo_v1_resource_limits_set_max_xmp_bytes(struct stegoeggo_v1_resource_limits_t *limits,
                                                                     size_t value,
                                                                     struct stegoeggo_v1_error_t **out_error);

uint8_t stegoeggo_v1_verification_report_authenticated(const struct stegoeggo_v1_verification_report_t *report);

stegoeggo_v1_evidence_strength_t stegoeggo_v1_verification_report_evidence_strength(const struct stegoeggo_v1_verification_report_t *report);

void stegoeggo_v1_verification_report_free(struct stegoeggo_v1_verification_report_t *report);

struct stegoeggo_v1_buffer_t *stegoeggo_v1_verification_report_json(const struct stegoeggo_v1_verification_report_t *report);

uint8_t stegoeggo_v1_verification_report_rights_found(const struct stegoeggo_v1_verification_report_t *report);

stegoeggo_v1_verification_status_t stegoeggo_v1_verification_report_status(const struct stegoeggo_v1_verification_report_t *report);

stegoeggo_v1_status_t stegoeggo_v1_verify(const uint8_t *data,
                                          size_t data_len,
                                          const uint8_t *mac_key,
                                          size_t mac_key_len,
                                          const struct stegoeggo_v1_resource_limits_t *limits,
                                          struct stegoeggo_v1_verification_report_t **out_report,
                                          struct stegoeggo_v1_error_t **out_error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* stegoeggo */
