//! Image protection library for embedding legal-notice and rights-reservation metadata,
//! with optional steganographic markers for redundant evidence.
//!
//! Embeds rights-reservation and AI-training restriction notices into images, with
//! optional best-effort steganographic markers for redundant evidence. Metadata
//! injection is the primary deterrence mechanism; steganographic payloads are a
//! supplementary channel that may survive casual modification.
//!
//! # Protection Levels
//!
//! - `Disabled`: No protection applied
//! - `Light`: Metadata injection plus minimal seed stego (Q-table seed for JPEG,
//!   LSB redundancy=1 for PNG/WebP). Metadata is the primary evidence channel.
//! - `Standard`: Steganography + metadata injection. Stego is a redundant
//!   best-effort marker; metadata remains the primary deterrence mechanism.
//!
//! # Protection Layers
//!
//! Each protection level applies one or more layers:
//! 1. **Steganography** - Optional hidden LSB payload (PNG, lossless WebP) or DCT perturbation (JPEG). A redundant best-effort evidence channel. Lossy WebP is not supported.
//! 2. **Metadata Injection** - Visible rights-reservation and AI-training restriction metadata (XMP, IPTC, EXIF). This is the primary deterrence mechanism.
//!
//! # JPEG/WebP/PNG Format Notes
//!
//! Steganographic robustness varies by format — these are format realities, not
//! implementation limitations. JPEG's lossy compression inherently limits
//! steganographic payload survival. For JPEG, the library stores a seed in
//! quantization tables when those tables are preserved and uses F5-style DCT
//! coefficient embedding for baseline JPEGs. Pixel-based stego payloads may not
//! survive JPEG re-compression. Metadata injection is unaffected by format choice
//! and remains the primary evidence channel regardless.
//! **For maximum steganographic verifiability, use PNG output format.**
//!
//! Verification priority for JPEG: metadata seed extraction > DCT quantization table
//! seed > DCT coefficient extraction > pixel-based extraction.
//!
//! # JPEG-in/JPEG-out Fast Path
//!
//! When using `process_image_bytes` with JPEG input and JPEG output, the library
//! takes a byte-only fast path that operates directly on DCT coefficients, avoiding
//! decode/encode cycles. This path applies DCT steganography (F5 embedding) and
//! metadata injection. For progressive JPEGs, the progressive encoding is preserved.
//!
//! # Security Considerations
//!
//! The library supports two verification profiles:
//!
//! **Without a MAC key** (legal-notice mode): Steganographic payload verification
//! uses a non-cryptographic CRC32 checksum with ECC redundancy. An attacker can
//! forge valid-looking payloads, but this is acceptable because visible metadata
//! markers prove intent and rights reservation. No MAC key is required for the
//! legal-notice use case.
//!
//! **With a MAC key** (authenticated provenance mode): The library uses
//! HMAC-SHA256 for cryptographic payload verification. This proves the hidden
//! payload was generated by a party with the configured secret, adding
//! authenticated provenance evidence. Use this when you need cryptographic
//! integrity for the steganographic channel:
//!
//! ```no_run
//! use stegoeggo::{ProtectionContext, ProtectionLevel};
//!
//! let ctx = ProtectionContext::default()
//!     .with_mac_key(b"your-secret-key".to_vec());
//! ```
//!
//! The primary deterrence mechanism is **visible metadata injection** (XMP, IPTC,
//! EXIF markers) — not the steganographic layer. Even if an attacker strips the
//! stego payload, the visible metadata markers remain as evidence of protection
//! and legal warnings.
//!
//! # WAF-Optimized Usage
//!
//! ```no_run
//! use stegoeggo::{process_image_bytes, ProtectionContext, ProtectionLevel, ImageOutputFormat};
//!
//! # fn main() -> Result<(), Box<dyn std::error::Error>> {
//! let ctx = ProtectionContext::new(0.5, 42)
//!     .with_format(ImageOutputFormat::Png)
//!     .with_mac_key(b"shared-verification-key".to_vec())
//!     .with_stego_redundancy(2)      // Lower = faster
//!     .with_jpeg_quality(85)        // Lower = smaller files
//!     .with_progressive_jpeg(true); // Progressive rendering for web
//!
//! let input_bytes = std::fs::read("image.png")?;
//! let (protected, warnings) =
//!     stegoeggo::process_image_bytes_with_warnings(&input_bytes, ProtectionLevel::Standard, &ctx)?;
//! // Reverse proxies should log or enforce warnings before serving.
//! # Ok(())
//! # }
//! ```
//!
//! Legal Metadata
//!
//! Embed copyright and usage restrictions in images for IP protection.
//!
//! ```rust
//! use stegoeggo::{ProtectionContext, LegalMetadata, ProtectionLevel};
//!
//! let ctx = ProtectionContext::default()
//!     .with_legal_metadata(
//!         LegalMetadata::new()
//!             .with_copyright_holder("Example Corp")
//!             .with_contact_email("legal@example.com")
//!             .with_usage_terms("All Rights Reserved. No AI training permitted.")
//!     );
//! ```
//!
//! # Feature Flags
//!
//! | Feature | Description |
//! |---------|-------------|
//! | `async` | Enables Tokio-based async wrappers. Canonical: `process_request_bytes_async`, `process_request_bytes_with_warnings_async`, `process_request_bytes_with_report_async`; legacy level/context wrappers remain as compatibility adapters |
//! | `signatures` | Enables Ed25519 signing via `ed25519-dalek` for provenance claims and detached manifests |
//! | `detached-manifest` | Enables signed sidecar manifest support |
//! | `iscc` | Enables ISCC content identifier computation (`compute_content_identifiers`, etc.) |
//! | `conformance` | Enables the conformance harness binary and manifest parsing (TOML) |
//! | `parallel` | Enables Rayon-based parallel batch processing. Canonical: `process_request_bytes_parallel`, `process_request_bytes_with_warnings_parallel`, `process_request_bytes_with_report_parallel`; legacy level/context batch functions remain as compatibility adapters |
//! | `test-seeds` | Enables fallback seed guessing during verification (tries common test/dev seeds). Used by the CLI; not recommended for library consumers |
//! | `fuzz` | Enables bounded JPEG dimension inspection for fuzz harnesses. It does not expose parser or coefficient types |
//!
//! New processing features must be expressed in `ProtectionRequest` /
//! `ProcessingOptions` / `ProtectionChannels` first. Legacy
//! `ProtectionContext` builders may only translate into those fields when
//! compatibility requires it.
//!
//! # Tiled Steganography
//!
//! For crop-resistant protection, enable tiled mode. The full payload is embedded
//! in each `tile_size × tile_size` tile independently, so any crop containing at
//! least one intact tile is recoverable:
//!
//! ```no_run
//! use stegoeggo::{ProtectionContext, ProtectionLevel};
//!
//! # fn main() -> Result<(), Box<dyn std::error::Error>> {
//! let ctx = ProtectionContext::new(0.5, 42)
//!     .with_tile_size(64);          // 64×64 tiles
//! # let img_bytes = std::fs::read("image.png")?;
//! let protected = stegoeggo::process_image_bytes(&img_bytes, ProtectionLevel::Standard, &ctx)?;
//! # Ok(())
//! # }
//! ```
//!
//! # Async API
//!
//! For Tokio-based services (WAFs, CDN edge workers), use the request-based
//! async variants. Each calls its synchronous canonical counterpart inside one
//! `spawn_blocking` closure:
//!
//! ```no_run
//! use stegoeggo::{process_request_bytes_async, ProtectionRequest, RightsNotice, RightsPolicy};
//!
//! # async fn example() -> Result<(), Box<dyn std::error::Error>> {
//! # let img_bytes = std::fs::read("image.png")?;
//! let request = ProtectionRequest::with_hidden_marker(
//!     RightsNotice::new(),
//!     RightsPolicy::ProhibitedAiMlTraining,
//! )
//! .with_seed(42);
//! let protected = process_request_bytes_async(img_bytes, request).await?;
//! # Ok(())
//! # }
//! ```
//!
//! # Parallel Batch Processing
//!
//! Process multiple byte buffers concurrently using Rayon with one shared
//! request. Output order matches input order:
//!
//! ```no_run
//! use stegoeggo::{process_request_bytes_parallel, ProtectionRequest, RightsNotice, RightsPolicy};
//!
//! # fn main() -> Result<(), Box<dyn std::error::Error>> {
//! let images: Vec<Vec<u8>> = vec![std::fs::read("a.png")?, std::fs::read("b.png")?];
//! let request = ProtectionRequest::with_hidden_marker(
//!     RightsNotice::new(),
//!     RightsPolicy::ProhibitedAiMlTraining,
//! )
//! .with_seed(42);
//! let results = process_request_bytes_parallel(&images, &request)?;
//! # Ok(())
//! # }
//! ```
//!
//! # Warnings API
//!
//! `process_request_bytes_with_warnings` returns both the protected bytes and
//! any warnings about the protection process (e.g., progressive JPEG fallback,
//! insufficient DCT capacity):
//!
//! ```no_run
//! use stegoeggo::{process_request_bytes_with_warnings, ProtectionRequest, RightsNotice, RightsPolicy};
//!
//! # fn main() -> Result<(), Box<dyn std::error::Error>> {
//! # let img_bytes = std::fs::read("image.png")?;
//! let request = ProtectionRequest::with_hidden_marker(
//!     RightsNotice::new(),
//!     RightsPolicy::ProhibitedAiMlTraining,
//! )
//! .with_seed(42);
//! let (protected, warnings) =
//!     process_request_bytes_with_warnings(&img_bytes, &request)?;
//!
//! for w in &warnings {
//!     eprintln!("Warning: {w}");
//! }
//! # Ok(())
//! # }
//! ```

#![forbid(unsafe_code)]
#![warn(missing_docs)]
#![cfg_attr(docsrs, feature(doc_cfg))]

#[cfg(feature = "conformance")]
#[cfg_attr(docsrs, doc(cfg(feature = "conformance")))]
pub mod conformance;
pub mod error;
/// V3 payload wire format: header, parser, types, and errors.
pub mod payload_v3;
/// Provenance claim model for rights/provenance assertions about images.
pub mod provenance;
/// Resource limits for parser hardening against malformed or adversarial inputs.
pub mod resource_limits;
pub mod traits;
/// Core types: protection levels, configuration, legal metadata, and verification results.
#[allow(deprecated)]
pub mod types;
/// Structured verification report and builder for legal-notice and stego verification.
pub mod verification;

pub(crate) mod protected;
/// Generic carrier APIs for arbitrary payloads.
///
/// This module re-exports the application-neutral
/// [`stegoeggo_stego`](https://docs.rs/stegoeggo-stego) carrier crate so
/// direct callers can use the same primitive operations without engaging
/// the StegoEggo rights/policy surface. For standalone generic use, prefer
/// the dedicated crate directly — it has its own package and public API
/// surface, and is the documented public home for these types.
pub mod stego {
    pub use stegoeggo_stego::error;
    pub use stegoeggo_stego::frame;
    pub use stegoeggo_stego::jpeg;
    pub use stegoeggo_stego::lsb;
    pub use stegoeggo_stego::types;
    pub use stegoeggo_stego::{
        CapacityReport, EmbedOutcome, EmbedOutcomeSummary, EmbedPath, EmbedReport, EmbedStatus,
        InPlaceEmbedReport, JpegUnsupportedReason, StegoError, StegoResult, TileConfig,
        DEFAULT_TILE_SIZE, MAX_TILED_ORIGINS,
    };
}
pub(crate) mod container_walk;
pub(crate) mod util;
pub(crate) mod webp_container;

pub(crate) mod xmp;

mod pipeline;

#[cfg(feature = "async")]
pub mod async_api;

#[cfg(feature = "signatures")]
#[cfg_attr(docsrs, doc(cfg(feature = "signatures")))]
pub mod signing;

#[cfg(feature = "detached-manifest")]
#[cfg_attr(docsrs, doc(cfg(feature = "detached-manifest")))]
pub mod detached;

pub use error::{Error, Result};
pub use resource_limits::{ResourceLimits, ResourceUsage};
pub use stego::{EmbedOutcomeSummary, EmbedPath, EmbedStatus};
pub use types::{AuthenticationMode, HiddenMarkerMode, ProcessingOptions};
#[allow(deprecated)]
pub use types::{
    DmiValue, EvidenceChannel, EvidenceProfile, EvidenceStrength, ExecutionReport,
    ImageOutputFormat, LegalMetadata, LocalizedText, MetadataUpdatePolicy, NoticeVerification,
    NoticeVerificationBuilder, ProtectionChannels, ProtectionConfig, ProtectionContext,
    ProtectionLevel, ProtectionPreset, ProtectionRequest, ProtectionWarning,
    ResolvedProtectionPlan, RightsNotice, RightsPolicy, RightsSignalKind, VerificationResult,
    VerificationStatus, WarningCategory, WarningSeverity, DEFAULT_OUTPUT_FORMAT,
    PLUS_DATA_MINING_PROPERTY, PLUS_NAMESPACE,
};

pub use traits::Protector;

#[allow(deprecated)]
pub use protected::metadata_trap::MetadataTrapProtector;
pub use protected::metadata_trap::RightsMetadataProtector;
pub use protected::passthrough::PassthroughProtector;
pub use protected::steganography::{SteganographyProtector, StegoPayload};

pub use stego::jpeg::is_progressive_jpeg;

/// Perform bounded JPEG structural inspection for fuzzing.
///
/// This feature-gated helper intentionally returns only image dimensions. The
/// carrier crate keeps parsed headers and coefficient maps private.
#[cfg(feature = "fuzz")]
pub fn parse_jpeg_for_fuzz(data: &[u8]) -> stego::StegoResult<(u32, u32)> {
    let info = stego::jpeg::inspect(data, 256, 65535)?;
    Ok((info.width, info.height))
}

pub use util::image::{
    compute_image_hash, detect_image_format, encode_image, encode_image_with_options,
    load_image_from_bytes,
};

#[cfg(feature = "iscc")]
#[cfg_attr(docsrs, doc(cfg(feature = "iscc")))]
#[allow(deprecated)]
pub use util::iscc::{
    compute_content_identifiers, compute_content_identifiers_from_bytes,
    compute_content_identifiers_from_bytes_with_metadata,
    compute_content_identifiers_with_metadata, compute_iscc, compute_iscc_from_bytes,
    compute_iscc_from_bytes_with_metadata, compute_iscc_with_metadata, ContentIdentifiers, Iscc,
};
pub use util::seed::generate_random_seed;

#[cfg(feature = "async")]
pub use async_api::{
    process_image_async, process_image_bytes_async, process_image_bytes_with_warnings_async,
    process_request_bytes_async, process_request_bytes_with_report_async,
    process_request_bytes_with_warnings_async, verify_image_bytes_async,
};

#[cfg(all(feature = "async", feature = "parallel"))]
pub use async_api::{
    process_images_bytes_parallel_async, process_images_parallel_async,
    process_request_bytes_parallel_async, process_request_bytes_with_report_parallel_async,
    process_request_bytes_with_warnings_parallel_async,
};

use image::DynamicImage;
use image::GenericImageView;
use std::borrow::Cow;

/// Main pipeline for applying protection to images.
///
/// Coordinates between different protector implementations based on the
/// selected protection level. Create one via [`ProtectionPipeline::new`]
/// or use the convenience functions ([`process_image`], [`process_image_bytes`]).
#[non_exhaustive]
pub struct ProtectionPipeline {}

impl Clone for ProtectionPipeline {
    fn clone(&self) -> Self {
        Self::new()
    }
}

impl ProtectionPipeline {
    /// Create a new ProtectionPipeline with default protectors.
    pub fn new() -> Self {
        Self {}
    }

    fn validate_dimensions(img: &DynamicImage, max_dim: Option<u32>) -> Result<()> {
        if let Some(max) = max_dim {
            let (width, height) = img.dimensions();
            if width > max || height > max {
                return Err(Error::ImageDecode(format!(
                    "Image dimensions {}x{} exceed maximum allowed {}",
                    width, height, max
                )));
            }
        }
        Ok(())
    }

    /// Process an image with the specified protection level.
    ///
    /// Delegates to the canonical request/plan execution path used by the
    /// top-level [`process_image`] function. `Disabled` short-circuits to a
    /// borrowed no-op passthrough.
    pub fn process<'a>(
        &'a self,
        img: &'a DynamicImage,
        level: ProtectionLevel,
        ctx: &ProtectionContext,
    ) -> Result<Cow<'a, DynamicImage>> {
        Self::validate_dimensions(img, ctx.max_dimension())?;

        if level == ProtectionLevel::Disabled {
            return Ok(Cow::Borrowed(img));
        }

        Ok(Cow::Owned(process_image_ref(img, level, ctx)?))
    }

    /// Process image bytes with the specified protection level.
    ///
    /// Delegates to the canonical [`process_image_bytes`] entry point so
    /// `ProtectionPipeline::process_bytes` and the top-level byte API
    /// produce identical results for the same `(level, ctx)` inputs.
    pub fn process_bytes(
        &self,
        img_bytes: &[u8],
        level: ProtectionLevel,
        ctx: &ProtectionContext,
    ) -> Result<Vec<u8>> {
        if level == ProtectionLevel::Disabled {
            return Ok(img_bytes.to_vec());
        }
        process_image_bytes(img_bytes, level, ctx)
    }
}

impl Default for ProtectionPipeline {
    fn default() -> Self {
        Self::new()
    }
}

/// Process an image with the specified protection level.
///
/// Takes an owned DynamicImage and returns a processed image.
///
/// # Errors
///
/// Returns [`Error::ImageDecode`] if the image dimensions exceed `max_dimension`.
/// Returns [`Error::ImageEncode`] or [`Error::Steganography`] if encoding or
/// embedding fails.
#[must_use = "the protected image should be saved or used"]
pub fn process_image(
    img: DynamicImage,
    level: ProtectionLevel,
    ctx: &ProtectionContext,
) -> Result<DynamicImage> {
    if level == ProtectionLevel::Disabled {
        return Ok(img);
    }
    process_image_ref(&img, level, ctx)
}

fn process_image_ref(
    img: &DynamicImage,
    level: ProtectionLevel,
    ctx: &ProtectionContext,
) -> Result<DynamicImage> {
    ctx.validate()?;
    ProtectionPipeline::validate_dimensions(img, ctx.max_dimension())?;
    if level == ProtectionLevel::Disabled {
        return Ok(img.clone());
    }
    let request = request_from_legacy(level, ctx);
    let format = ctx
        .output_format()
        .or_else(|| ctx.input_format())
        .unwrap_or(crate::types::DEFAULT_OUTPUT_FORMAT);
    let plan = resolve_request(&request, format)?;
    let steganography = SteganographyProtector::new();

    match plan.channels().hidden_marker {
        HiddenMarkerMode::Disabled => Ok(img.clone()),
        HiddenMarkerMode::SeedOnly => {
            if plan.output_format() == crate::types::ImageOutputFormat::Jpeg {
                let jpeg_bytes = crate::util::image::encode_image_with_options(
                    img,
                    Some(plan.output_format()),
                    plan.processing().progressive_jpeg,
                    plan.processing().jpeg_quality,
                )?;
                let with_seed = steganography.apply_qtable_seed_bytes(&jpeg_bytes, plan.seed())?;
                return image::load_from_memory(&with_seed)
                    .map_err(|e| Error::ImageDecode(e.to_string()));
            }

            let mut rgba = img.to_rgba8();
            SteganographyProtector::embed_seed_lsb_fallback_pub(&mut rgba, plan.seed());
            Ok(DynamicImage::ImageRgba8(rgba))
        }
        HiddenMarkerMode::BestEffort => {
            if plan.output_format() == crate::types::ImageOutputFormat::Jpeg {
                let jpeg_bytes = crate::util::image::encode_image_with_options(
                    img,
                    Some(plan.output_format()),
                    plan.processing().progressive_jpeg,
                    plan.processing().jpeg_quality,
                )?;
                let with_stego =
                    steganography.apply_dct_stego_bytes_from_plan(&jpeg_bytes, &plan, None)?;
                let (output, _) = with_stego.into_parts();
                return image::load_from_memory(&output)
                    .map_err(|e| Error::ImageDecode(e.to_string()));
            }
            let (processed, _summary) =
                steganography.apply_lsb_to_image_with_summary_from_plan(img, &plan, None)?;
            Ok(processed)
        }
        HiddenMarkerMode::Tiled { tile_size } => {
            if plan.output_format() == crate::types::ImageOutputFormat::Jpeg {
                let jpeg_bytes = crate::util::image::encode_image_with_options(
                    img,
                    Some(plan.output_format()),
                    plan.processing().progressive_jpeg,
                    plan.processing().jpeg_quality,
                )?;
                let with_stego = steganography.apply_dct_stego_bytes_from_plan(
                    &jpeg_bytes,
                    &plan,
                    Some(tile_size),
                )?;
                let (output, _) = with_stego.into_parts();
                return image::load_from_memory(&output)
                    .map_err(|e| Error::ImageDecode(e.to_string()));
            }
            let (processed, _summary) = steganography.apply_lsb_to_image_with_summary_from_plan(
                img,
                &plan,
                Some(tile_size),
            )?;
            Ok(processed)
        }
    }
}

/// Process multiple images in parallel.
///
/// Takes a slice of images and returns a vector of processed images.
/// Uses Rayon for parallel processing.
///
/// # Examples
///
/// ```no_run
/// use stegoeggo::{process_images_parallel, ProtectionContext, ProtectionLevel};
/// use image::DynamicImage;
///
/// let images: Vec<DynamicImage> = vec![
///     image::open("image1.png").unwrap(),
///     image::open("image2.png").unwrap(),
/// ];
/// let ctx = ProtectionContext::new(0.5, 42);
/// let protected = process_images_parallel(&images, ProtectionLevel::Standard, &ctx).unwrap();
/// ```
///
/// # Errors
///
/// Returns the first error encountered from any image processing call.
#[cfg(feature = "parallel")]
#[cfg_attr(docsrs, doc(cfg(feature = "parallel")))]
#[must_use = "the protected images should be saved or used"]
pub fn process_images_parallel(
    images: &[DynamicImage],
    level: ProtectionLevel,
    ctx: &ProtectionContext,
) -> Result<Vec<DynamicImage>> {
    use rayon::prelude::*;
    images
        .par_iter()
        .map(|img| process_image(img.clone(), level, ctx))
        .collect()
}

/// Process multiple images in parallel (bytes variant).
///
/// Compatibility adapter over the legacy level/context API. New code should
/// prefer [`process_request_bytes_parallel`].
///
/// Takes a slice of image bytes and returns a vector of processed image bytes.
///
/// # Examples
///
/// ```no_run
/// use stegoeggo::{process_images_bytes_parallel, ProtectionContext, ProtectionLevel};
///
/// let images: Vec<Vec<u8>> = vec![
///     std::fs::read("image1.png").unwrap(),
///     std::fs::read("image2.png").unwrap(),
/// ];
/// let ctx = ProtectionContext::new(0.5, 42);
/// let protected = process_images_bytes_parallel(&images, ProtectionLevel::Standard, &ctx).unwrap();
/// ```
///
/// # Errors
///
/// Returns the first error encountered from any image processing call.
#[cfg(feature = "parallel")]
#[cfg_attr(docsrs, doc(cfg(feature = "parallel")))]
#[must_use = "the protected image bytes should be saved or used"]
pub fn process_images_bytes_parallel(
    images: &[Vec<u8>],
    level: ProtectionLevel,
    ctx: &ProtectionContext,
) -> Result<Vec<Vec<u8>>> {
    use rayon::prelude::*;
    images
        .par_iter()
        .map(|img_bytes| process_image_bytes(img_bytes, level, ctx))
        .collect()
}

/// Process multiple image byte buffers in parallel using one shared [`ProtectionRequest`].
///
/// Canonical request-based batch API. Reuses [`process_request_bytes`] through
/// Rayon and preserves input order in the output. This is the narrowest useful
/// batch contract: one request applied to many inputs. There is no second batch
/// executor and no per-item request form.
///
/// # Examples
///
/// ```no_run
/// use stegoeggo::{process_request_bytes_parallel, ProtectionRequest, RightsNotice, RightsPolicy};
///
/// let images: Vec<Vec<u8>> = vec![
///     std::fs::read("image1.png").unwrap(),
///     std::fs::read("image2.png").unwrap(),
/// ];
/// let request = ProtectionRequest::with_hidden_marker(
///     RightsNotice::new(),
///     RightsPolicy::ProhibitedAiMlTraining,
/// )
/// .with_seed(42);
/// let protected = process_request_bytes_parallel(&images, &request).unwrap();
/// ```
///
/// # Errors
///
/// Returns the first error encountered from any image processing call.
#[cfg(feature = "parallel")]
#[cfg_attr(docsrs, doc(cfg(feature = "parallel")))]
#[must_use = "the protected image bytes should be saved or used"]
pub fn process_request_bytes_parallel(
    images: &[Vec<u8>],
    request: &ProtectionRequest,
) -> Result<Vec<Vec<u8>>> {
    use rayon::prelude::*;
    images
        .par_iter()
        .map(|img_bytes| process_request_bytes(img_bytes, request))
        .collect()
}

/// Process multiple image byte buffers in parallel using one shared request, with warnings.
///
/// Canonical request-based batch API. Reuses
/// [`process_request_bytes_with_warnings`] through Rayon and preserves input
/// order.
///
/// # Errors
///
/// Returns the first error encountered from any image processing call.
#[cfg(feature = "parallel")]
#[cfg_attr(docsrs, doc(cfg(feature = "parallel")))]
#[must_use = "the protected image bytes and warnings should be used"]
pub fn process_request_bytes_with_warnings_parallel(
    images: &[Vec<u8>],
    request: &ProtectionRequest,
) -> Result<Vec<(Vec<u8>, Vec<ProtectionWarning>)>> {
    use rayon::prelude::*;
    images
        .par_iter()
        .map(|img_bytes| process_request_bytes_with_warnings(img_bytes, request))
        .collect()
}

/// Process multiple image byte buffers in parallel using one shared request, with reports.
///
/// Canonical request-based batch API. Reuses
/// [`process_request_bytes_with_report`] through Rayon and preserves input
/// order.
///
/// # Errors
///
/// Returns the first error encountered from any image processing call.
#[cfg(feature = "parallel")]
#[cfg_attr(docsrs, doc(cfg(feature = "parallel")))]
#[must_use = "the protected image bytes and reports should be used"]
pub fn process_request_bytes_with_report_parallel(
    images: &[Vec<u8>],
    request: &ProtectionRequest,
) -> Result<Vec<(Vec<u8>, ExecutionReport)>> {
    use rayon::prelude::*;
    images
        .par_iter()
        .map(|img_bytes| process_request_bytes_with_report(img_bytes, request))
        .collect()
}

/// Resolve a [`ProtectionRequest`] into an immutable execution plan.
///
/// This validates all input combinations and produces an execution plan
/// that pipeline stages consume. Resolution runs once before any image
/// processing occurs.
pub fn resolve_request(
    request: &ProtectionRequest,
    input_format: ImageOutputFormat,
) -> Result<ResolvedProtectionPlan> {
    protected::resolve::resolve_request(request, input_format)
}

fn request_from_legacy(level: ProtectionLevel, ctx: &ProtectionContext) -> ProtectionRequest {
    let rights_metadata = ctx.effective_metadata_injection();

    let channels = match level {
        ProtectionLevel::Disabled => ProtectionChannels {
            rights_metadata: false,
            hidden_marker: HiddenMarkerMode::Disabled,
            authentication: AuthenticationMode::None,
        },
        ProtectionLevel::Light | ProtectionLevel::Standard => {
            let authentication = if ctx.mac_key().is_some() {
                AuthenticationMode::Hmac
            } else {
                AuthenticationMode::None
            };
            let hidden_marker = match level {
                ProtectionLevel::Light => HiddenMarkerMode::SeedOnly,
                ProtectionLevel::Standard => ctx
                    .tile_size()
                    .filter(|&s| s > 0)
                    .map_or(HiddenMarkerMode::BestEffort, |tile_size| {
                        HiddenMarkerMode::Tiled { tile_size }
                    }),
                ProtectionLevel::Disabled => {
                    debug_assert!(
                        false,
                        "Disabled is handled by the outer match; unreachable here"
                    );
                    HiddenMarkerMode::SeedOnly
                }
            };
            ProtectionChannels {
                rights_metadata,
                hidden_marker,
                authentication,
            }
        }
    };

    let policy = if !rights_metadata {
        RightsPolicy::Unspecified
    } else {
        ctx.dmi_value()
            .map(RightsPolicy::from)
            .unwrap_or_else(|| level.default_policy())
    };

    let mut notice = RightsNotice::default();
    let effective_dmi = ctx.dmi_value().unwrap_or_else(|| DmiValue::from(policy));
    notice = notice.with_dmi(effective_dmi);
    notice = notice.with_seed(ctx.seed());

    let legal_claims_decision = legal_claims_decision(ctx);

    let output_format = ctx.output_format();
    let mut request = ProtectionRequest::new(notice, policy, channels)
        .with_seed(ctx.seed())
        .with_intensity(ctx.intensity())
        .with_jpeg_quality(ctx.jpeg_quality());

    if let Some(fmt) = output_format {
        request = request.with_output_format(fmt);
    }
    if ctx.progressive_jpeg() {
        request = request.with_progressive_jpeg();
    }
    if legal_claims_decision == LegalClaimsDecision::Include {
        if let Some(meta) = ctx.legal_metadata() {
            request = request.with_legal_metadata(meta.clone());
        }
    }
    if let Some(key) = ctx.mac_key() {
        request = request.with_mac_key(key.to_vec());
    }
    request = request.with_resource_limits(ctx.resource_limits());

    let mut processing = request.processing().clone();
    if let Some(max_dim) = ctx.max_dimension() {
        processing.max_dimension = Some(max_dim);
    }
    processing.metadata_update_policy = ctx.metadata_update_policy();
    if let Some(r) = ctx.stego_redundancy_field() {
        processing.stego_redundancy = Some(r);
    }
    if let Some(hash) = ctx.content_hash() {
        processing.content_hash = Some(hash);
    }
    if let Some(ts) = ctx.timestamp_override() {
        processing.timestamp_override = Some(ts.to_string());
    }
    request = request.with_processing(processing);

    request
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum LegalClaimsDecision {
    Include,
    Exclude,
}

fn legal_claims_decision(ctx: &ProtectionContext) -> LegalClaimsDecision {
    match ctx.inject_legal_claims() {
        Some(false) => LegalClaimsDecision::Exclude,
        Some(true) | None => LegalClaimsDecision::Include,
    }
}

/// Process image bytes with the specified protection level.
///
/// Automatically detects the input format from magic bytes and preserves
/// the output format. Returns the protected image as bytes. `Disabled`
/// protection is a byte-for-byte no-op and does not require format detection.
///
/// For JPEG-in/JPEG-out, this function takes a byte-only fast path that
/// operates on DCT coefficients directly, avoiding pixel decode/encode cycles.
///
/// # Examples
///
/// ```no_run
/// use stegoeggo::{process_image_bytes, ProtectionContext, ProtectionLevel};
///
/// let img_bytes: Vec<u8> = std::fs::read("input.png").unwrap();
/// let ctx = ProtectionContext::new(0.5, 42);
/// let protected = process_image_bytes(&img_bytes, ProtectionLevel::Standard, &ctx).unwrap();
/// std::fs::write("output.png", &protected).unwrap();
/// ```
///
/// # Errors
///
/// Returns [`Error::InvalidFormat`] if the image format cannot be determined
/// for `Light` or `Standard` protection.
/// Returns [`Error::ImageDecode`], [`Error::ImageEncode`], or
/// [`Error::Steganography`] if processing fails.
#[must_use = "the protected image bytes should be saved or used"]
pub fn process_image_bytes(
    img_bytes: &[u8],
    level: ProtectionLevel,
    ctx: &ProtectionContext,
) -> Result<Vec<u8>> {
    if level == ProtectionLevel::Disabled {
        return Ok(img_bytes.to_vec());
    }
    ctx.validate()?;
    if let Some(meta) = ctx.legal_metadata() {
        meta.validate()?;
    }
    let request = request_from_legacy(level, ctx);
    process_request_bytes(img_bytes, &request)
}

/// Process image bytes with protection level and return warnings about
/// degraded protection.
///
/// Like [`process_image_bytes`], but also returns a [`ProtectionWarning`] if
/// the protection was applied with reduced effectiveness. This is important
/// for legal defense use cases where the caller needs to know the actual
/// protection level applied.
///
/// This compatibility helper returns only the first warning. New reverse-proxy
/// integrations should prefer [`process_image_bytes_with_warnings`] so they can
/// log or enforce every warning emitted for the request.
///
/// # Examples
///
/// ```no_run
/// use stegoeggo::{process_image_bytes_with_info, ProtectionContext, ProtectionLevel};
///
/// let img_bytes: Vec<u8> = std::fs::read("input.jpg").unwrap();
/// let ctx = ProtectionContext::new(0.5, 42);
/// let (protected, warning) = process_image_bytes_with_info(
///     &img_bytes, ProtectionLevel::Standard, &ctx
/// ).unwrap();
/// if let Some(w) = warning {
///     eprintln!("Warning: {}", w);
/// }
/// ```
///
/// # Errors
///
/// Returns [`Error::InvalidFormat`] if the image format cannot be determined.
/// Returns [`Error::ImageDecode`], [`Error::ImageEncode`], or
/// [`Error::Steganography`] if processing fails.
pub fn process_image_bytes_with_info(
    img_bytes: &[u8],
    level: ProtectionLevel,
    ctx: &ProtectionContext,
) -> Result<(Vec<u8>, Option<ProtectionWarning>)> {
    let (bytes, warnings) = process_image_bytes_with_warnings(img_bytes, level, ctx)?;
    let warning = warnings.into_iter().next();
    Ok((bytes, warning))
}

/// Process image bytes with protection level and return all protection warnings.
///
/// Compatibility adapter over the legacy level/context API. Translates once
/// via `request_from_legacy()` into [`ProtectionRequest`] and delegates to the
/// canonical [`process_request_bytes_with_warnings`]. Canonical resolution,
/// routing, capacity handling, and runtime warnings are owned by the request
/// path; only compatibility-only presentation warnings are added here (see
/// below). New code should prefer `process_request_bytes_with_warnings`.
///
/// Compatibility-only warnings retained for 0.x callers:
/// - `MissingMacKey` when a legacy authenticated profile was selected without
///   a MAC key (the canonical request model reports this as `Error::Config`
///   for HMAC channels instead of a profile-driven warning).
/// - `ContradictoryLegalClaims` when `inject_legal_claims(false)` is combined
///   with non-empty legal metadata (the canonical request has no disable flag;
///   presence of legal metadata means include). The CLI rejects the same
///   combination as `EXIT_CONFIG` 2.
/// - `JpegReencodeFragile` for non-`Disabled` JPEG output (advisory fragility
///   note; the canonical path reports only resolution and runtime warnings).
///
/// `MetadataInjectionDisabled` and capacity warnings (`LsbCapacitySkipped`,
/// `DctCapacityInsufficient`, `ProgressiveJpegFallback`) come from the
/// canonical path and are not duplicated here. Compatibility warnings are
/// prepended before canonical warnings to preserve 0.x
/// `process_image_bytes_with_info` first-warning ordering.
///
/// # Errors
///
/// Returns [`Error::InvalidFormat`] if the image format cannot be determined.
/// Returns [`Error::ImageDecode`], [`Error::ImageEncode`], or
/// [`Error::Steganography`] if processing fails.
#[allow(deprecated)]
pub fn process_image_bytes_with_warnings(
    img_bytes: &[u8],
    level: ProtectionLevel,
    ctx: &ProtectionContext,
) -> Result<(Vec<u8>, Vec<ProtectionWarning>)> {
    if level == ProtectionLevel::Disabled {
        return Ok((img_bytes.to_vec(), Vec::new()));
    }

    ctx.validate()?;
    if let Some(meta) = ctx.legal_metadata() {
        meta.validate()?;
    }

    let request = request_from_legacy(level, ctx);
    let (bytes, canonical_warnings) = process_request_bytes_with_warnings(img_bytes, &request)?;

    let mut compat = Vec::new();
    if ctx.mac_key().is_none()
        && matches!(
            ctx.evidence_profile(),
            EvidenceProfile::AuthenticatedProvenance | EvidenceProfile::Maximal
        )
    {
        compat.push(ProtectionWarning::MissingMacKey);
    }
    if matches!(ctx.inject_legal_claims(), Some(false))
        && ctx.legal_metadata().is_some_and(|m| m.has_content())
    {
        compat.push(ProtectionWarning::ContradictoryLegalClaims);
    }
    if ImageOutputFormat::is_jpeg(&bytes) {
        compat.push(ProtectionWarning::JpegReencodeFragile);
    }

    let mut warnings = Vec::with_capacity(compat.len() + canonical_warnings.len());
    for w in compat.into_iter().chain(canonical_warnings) {
        if !warnings.contains(&w) {
            warnings.push(w);
        }
    }

    Ok((bytes, warnings))
}

/// Process image bytes using a [`ProtectionRequest`].
///
/// This is the canonical request-based API. It resolves the request into
/// an execution plan, then processes the image according to that plan.
/// Metadata-only requests produce same-format output without pixel decode.
///
/// # Errors
///
/// Returns [`Error::InvalidFormat`] if the image format cannot be determined.
/// Returns config errors if the request contains invalid combinations.
pub fn process_request_bytes(img_bytes: &[u8], request: &ProtectionRequest) -> Result<Vec<u8>> {
    request
        .resource_limits()
        .cloned()
        .unwrap_or_default()
        .check_input_size(img_bytes.len())?;
    let input_format = ImageOutputFormat::from_magic_bytes(img_bytes)
        .ok_or_else(|| Error::InvalidFormat("Unrecognized image format".to_string()))?;

    let plan = resolve_request(request, input_format)?;

    if let Some(meta) = plan.legal_metadata() {
        meta.validate()?;
    }

    let mut budget =
        crate::resource_limits::OperationObserver::new(plan.resource_limits(), img_bytes.len());
    pipeline::process_plan_bytes(img_bytes, &plan, &mut budget).map(|r| r.bytes)
}

/// Process image bytes using a [`ProtectionRequest`], returning warnings.
///
/// Like [`process_request_bytes`], but also returns any warnings about
/// degraded protection conditions.
pub fn process_request_bytes_with_warnings(
    img_bytes: &[u8],
    request: &ProtectionRequest,
) -> Result<(Vec<u8>, Vec<ProtectionWarning>)> {
    request
        .resource_limits()
        .cloned()
        .unwrap_or_default()
        .check_input_size(img_bytes.len())?;
    let input_format = ImageOutputFormat::from_magic_bytes(img_bytes)
        .ok_or_else(|| Error::InvalidFormat("Unrecognized image format".to_string()))?;

    let plan = resolve_request(request, input_format)?;

    if let Some(meta) = plan.legal_metadata() {
        meta.validate()?;
    }

    let mut all_warnings = plan.warnings().to_vec();

    let mut budget =
        crate::resource_limits::OperationObserver::new(plan.resource_limits(), img_bytes.len());
    let pipeline_result = pipeline::process_plan_bytes(img_bytes, &plan, &mut budget)?;

    if let Some(ref summary) = pipeline_result.embed_summary {
        let runtime = pipeline::warnings_from_embed_outcome(summary);
        for w in runtime {
            if !all_warnings.contains(&w) {
                all_warnings.push(w);
            }
        }
    }

    Ok((pipeline_result.bytes, all_warnings))
}

/// Process image bytes using a [`ProtectionRequest`], returning a full execution report.
///
/// This is the most informative request-based API. It resolves the request,
/// processes the image, and returns a detailed report of what was executed
/// and any degradation that occurred.
pub fn process_request_bytes_with_report(
    img_bytes: &[u8],
    request: &ProtectionRequest,
) -> Result<(Vec<u8>, ExecutionReport)> {
    request
        .resource_limits()
        .cloned()
        .unwrap_or_default()
        .check_input_size(img_bytes.len())?;
    let input_format = ImageOutputFormat::from_magic_bytes(img_bytes)
        .ok_or_else(|| Error::InvalidFormat("Unrecognized image format".to_string()))?;

    let plan = resolve_request(request, input_format)?;

    if let Some(meta) = plan.legal_metadata() {
        meta.validate()?;
    }

    let mut warnings = plan.warnings().to_vec();
    let output_format = plan.output_format();
    let format_transcoded = input_format != output_format;

    let mut budget =
        crate::resource_limits::OperationObserver::new(plan.resource_limits(), img_bytes.len());

    let pipeline_result = pipeline::process_plan_bytes(img_bytes, &plan, &mut budget)?;
    let result = pipeline_result.bytes;

    let stego_attempted = plan.channels().has_stego();

    let (stego_succeeded, embed_summary) = if stego_attempted {
        match pipeline_result.embed_summary {
            Some(summary) => {
                let runtime = pipeline::warnings_from_embed_outcome(&summary);
                for w in runtime {
                    if !warnings.contains(&w) {
                        warnings.push(w);
                    }
                }
                let succeeded = summary.is_embedded();
                (succeeded, Some(summary))
            }
            None => (false, None),
        }
    } else {
        (false, None)
    };

    let metadata_injected = if plan.channels().rights_metadata {
        protected::metadata_trap::RightsMetadataProtector::new()
            .has_stego_owned_metadata(&result, output_format)
    } else {
        false
    };

    budget.observe_alloc(result.len());
    let resource_usage = budget.finish(result.len());

    let report = ExecutionReport {
        effective_policy: plan.effective_policy(),
        effective_dmi: plan.effective_dmi(),
        metadata_injected,
        stego_attempted,
        stego_succeeded,
        format_transcoded,
        warnings,
        resource_usage: Some(resource_usage),
        embed_summary,
    };

    Ok((result, report))
}

/// Verify that image bytes contain a protection payload whose integrity can be proved.
///
/// Compatibility projection of the canonical [`VerificationReport`] (see
/// [`verify_image_bytes_report`]). Reports hidden-marker integrity only;
/// use `summary_status` on the report for rights-fallback semantics.
/// Stable and not deprecated.
///
/// # Returns
///
/// - [`VerificationStatus::Verified`] — protection data found and verification passed
/// - [`VerificationStatus::Invalid`] — protection data found but verification failed
///   (corrupted, malformed, unsupported version, missing/failed auth, or resource exhaustion)
/// - [`VerificationStatus::NotFound`] — no protection data found in the image
///
/// # Arguments
///
/// * `img_bytes` - Raw image bytes (PNG, JPEG, or WebP)
/// * `mac_key` - Optional MAC key for HMAC-SHA256 verification. Pass empty slice
///   for checksum-only verification.
///
/// # Examples
///
/// ```no_run
/// # let img_bytes: Vec<u8> = Vec::new();
/// match stegoeggo::verify_image_bytes(&img_bytes, &[]) {
///     stegoeggo::VerificationStatus::Verified => println!("Protected and verified"),
///     stegoeggo::VerificationStatus::Invalid => println!("Protected but verification failed"),
///     stegoeggo::VerificationStatus::NotFound => println!("No protection found"),
/// }
/// ```
pub fn verify_image_bytes(img_bytes: &[u8], mac_key: &[u8]) -> VerificationStatus {
    let facts = crate::verification::canonical::verify_canonical(img_bytes, mac_key);
    crate::verification::canonical::project_status_from_canonical(&facts)
}

/// Verify protection with custom resource limits.
///
/// Like [`verify_image_bytes`], but enforces the provided [`ResourceLimits`]
/// during extraction. Limits cap tile-origin scanning, fallback-seed iteration,
/// and payload size to prevent excessive work on adversarial inputs.
pub fn verify_image_bytes_with_limits(
    img_bytes: &[u8],
    mac_key: &[u8],
    limits: &ResourceLimits,
) -> VerificationStatus {
    let facts =
        crate::verification::canonical::verify_canonical_with_limits(img_bytes, mac_key, limits);
    crate::verification::canonical::project_status_from_canonical(&facts)
}

/// Verify protection with detailed results.
///
/// Like [`verify_image_bytes`], but returns a [`VerificationResult`] with
/// richer information about what was found and whether verification passed.
///
/// # Examples
///
/// ```no_run
/// use stegoeggo::{verify_image_bytes_detailed, VerificationResult};
///
/// let bytes = std::fs::read("protected.png").unwrap();
/// match verify_image_bytes_detailed(&bytes, b"my-key") {
///     VerificationResult::Verified { payload } => {
///         println!("Seed: {}, Intensity: {}", payload.seed(), payload.intensity());
///     }
///     VerificationResult::MetadataOnly { seed } => {
///         println!("Metadata seed found, but payload was not verified: {}", seed);
///     }
///     VerificationResult::Corrupted { .. } => println!("Protection found but corrupted"),
///     VerificationResult::NotFound => println!("No protection found"),
/// }
/// ```
pub fn verify_image_bytes_detailed(img_bytes: &[u8], mac_key: &[u8]) -> VerificationResult {
    let facts = crate::verification::canonical::verify_canonical(img_bytes, mac_key);
    crate::verification::canonical::project_result_from_canonical(&facts)
}

/// Verify protection with detailed results and custom resource limits.
///
/// Like [`verify_image_bytes_detailed`], but enforces the provided [`ResourceLimits`]
/// during extraction.
pub fn verify_image_bytes_detailed_with_limits(
    img_bytes: &[u8],
    mac_key: &[u8],
    limits: &ResourceLimits,
) -> VerificationResult {
    let facts =
        crate::verification::canonical::verify_canonical_with_limits(img_bytes, mac_key, limits);
    crate::verification::canonical::project_result_from_canonical(&facts)
}

/// Verify legal-notice metadata and steganographic status in a protected image.
///
/// Returns a [`NoticeVerification`] report containing the extracted legal-notice
/// fields (copyright holder, rights URL, AI constraints, etc.), the steganographic
/// verification status, and an evidence strength assessment.
///
/// Unlike [`verify_image_bytes`] and [`verify_image_bytes_detailed`], which focus
/// on steganographic payload integrity, this function also parses the legal-notice
/// metadata injected by the protection pipeline and reports which evidence channels
/// were found.
///
/// # Arguments
///
/// * `img_bytes` - Raw image bytes (PNG, JPEG, or WebP)
/// * `mac_key` - MAC key for HMAC-SHA256 authentication. Pass empty slice for
///   checksum-only verification.
///
/// # Examples
///
/// ```no_run
/// let img_bytes = std::fs::read("protected.png").unwrap();
/// let report = stegoeggo::verify_legal_notice(&img_bytes, b"my-mac-key");
///
/// if let Some(holder) = report.copyright_holder() {
///     println!("Copyright holder: {}", holder);
/// }
/// println!("Evidence strength: {}", report.evidence_strength());
/// ```
pub fn verify_legal_notice(img_bytes: &[u8], mac_key: &[u8]) -> NoticeVerification {
    let facts = crate::verification::canonical::verify_canonical(img_bytes, mac_key);
    crate::verification::canonical::project_notice_from_canonical(&facts)
}

/// Verify legal-notice metadata with custom resource limits.
///
/// Like [`verify_legal_notice`], but enforces the provided [`ResourceLimits`]
/// during extraction. Limits cap XMP size, metadata field counts, and
/// steganographic extraction bounds.
pub fn verify_legal_notice_with_limits(
    img_bytes: &[u8],
    mac_key: &[u8],
    limits: &ResourceLimits,
) -> NoticeVerification {
    let facts =
        crate::verification::canonical::verify_canonical_with_limits(img_bytes, mac_key, limits);
    crate::verification::canonical::project_notice_from_canonical(&facts)
}

/// Verify image bytes and return the canonical structured [`VerificationReport`].
///
/// This is the canonical verification operation for rich integrations. It performs
/// the single expensive rights-parse plus hidden-marker search once, then builds
/// the report. [`verify_image_bytes`], [`verify_image_bytes_detailed`], and
/// [`verify_legal_notice`] are compatibility projections derived from the same
/// canonical facts.
///
/// [`VerificationStatus`] remains stable and is not deprecated; it is the coarse
/// hidden-marker integrity projection of this report.
pub fn verify_image_bytes_report(
    img_bytes: &[u8],
    mac_key: &[u8],
) -> crate::verification::VerificationReport {
    let facts = crate::verification::canonical::verify_canonical(img_bytes, mac_key);
    crate::verification::canonical::project_report_from_canonical(&facts)
}

/// Verify image bytes with custom resource limits, returning the canonical report.
///
/// Like [`verify_image_bytes_report`], but enforces the provided [`ResourceLimits`]
/// during extraction.
pub fn verify_image_bytes_report_with_limits(
    img_bytes: &[u8],
    mac_key: &[u8],
    limits: &ResourceLimits,
) -> crate::verification::VerificationReport {
    let facts =
        crate::verification::canonical::verify_canonical_with_limits(img_bytes, mac_key, limits);
    crate::verification::canonical::project_report_from_canonical(&facts)
}

#[cfg(test)]
#[allow(deprecated)]
mod tests {
    use super::*;

    #[test]
    fn test_pipeline_disabled() {
        let pipeline = ProtectionPipeline::new();
        let img = DynamicImage::new_rgb8(10, 10);

        let result = pipeline.process(
            &img,
            ProtectionLevel::Disabled,
            &ProtectionContext::default().with_seed(42),
        );
        assert!(result.is_ok());
    }

    #[test]
    fn test_pipeline_all_levels() {
        let pipeline = ProtectionPipeline::new();
        let img = DynamicImage::new_rgb8(10, 10);

        for level in &[
            ProtectionLevel::Disabled,
            ProtectionLevel::Light,
            ProtectionLevel::Standard,
        ] {
            let result =
                pipeline.process(&img, *level, &ProtectionContext::default().with_seed(42));
            assert!(result.is_ok(), "Failed for level: {:?}", level);
        }
    }

    #[test]
    fn test_process_image_bytes() {
        use image::ImageEncoder;

        let img = DynamicImage::new_rgb8(10, 10);
        let mut buffer = Vec::new();
        {
            let encoder = image::codecs::png::PngEncoder::new(&mut buffer);
            let rgb = img.to_rgb8();
            encoder
                .write_image(&rgb, 10, 10, image::ExtendedColorType::Rgb8)
                .unwrap();
        }

        let result = process_image_bytes(
            &buffer,
            ProtectionLevel::Standard,
            &ProtectionContext::default().with_seed(42),
        );
        assert!(result.is_ok());
    }

    #[test]
    fn disabled_process_image_bytes_is_byte_for_byte_noop() {
        let input = b"not an image";
        let ctx = ProtectionContext::default().with_seed(42);

        let result = process_image_bytes(input, ProtectionLevel::Disabled, &ctx).unwrap();

        assert_eq!(result, input);
    }

    #[test]
    fn disabled_process_image_bytes_with_warnings_is_byte_for_byte_noop() {
        let input = b"not an image";
        let ctx = ProtectionContext::default()
            .with_seed(42)
            .with_metadata_injection(false);

        let (result, warnings) =
            process_image_bytes_with_warnings(input, ProtectionLevel::Disabled, &ctx).unwrap();

        assert_eq!(result, input);
        assert!(warnings.is_empty());
    }

    #[test]
    fn test_end_to_end_protection_verification() {
        let pipeline = ProtectionPipeline::new();
        let img = DynamicImage::new_rgb8(64, 64);

        let ctx = ProtectionContext::default()
            .with_seed(42)
            .with_intensity(0.5);

        let protected = pipeline
            .process(&img, ProtectionLevel::Standard, &ctx)
            .unwrap();

        let stego = SteganographyProtector::new();
        let verified = stego.verify_payload(&protected);

        assert!(verified, "Payload should be verified after protection");
    }

    #[test]
    fn test_process_bytes_and_verify() {
        use image::ImageEncoder;

        let img = DynamicImage::new_rgb8(32, 32);
        let mut input_bytes = Vec::new();
        {
            let encoder = image::codecs::png::PngEncoder::new(&mut input_bytes);
            let rgb = img.to_rgb8();
            encoder
                .write_image(&rgb, 32, 32, image::ExtendedColorType::Rgb8)
                .unwrap();
        }

        let ctx = ProtectionContext::default()
            .with_seed(12345)
            .with_intensity(0.7);

        let protected_bytes =
            process_image_bytes(&input_bytes, ProtectionLevel::Standard, &ctx).unwrap();

        assert!(!protected_bytes.is_empty());
        // Output should differ from input when intensity > 0.
        // Size difference alone is insufficient (metadata injection always
        // changes size), so also verify content differs for non-zero intensity.
        assert!(
            protected_bytes.len() != input_bytes.len() || ctx.intensity() == 0.0,
            "Protected bytes should differ from input at intensity {}",
            ctx.intensity()
        );
    }

    #[test]
    fn test_different_seeds_different_output() {
        let pipeline = ProtectionPipeline::new();
        let img = DynamicImage::new_rgb8(32, 32);

        let ctx1 = ProtectionContext::default().with_seed(42);
        let ctx2 = ProtectionContext::default().with_seed(99);

        let result1 = pipeline
            .process(&img, ProtectionLevel::Standard, &ctx1)
            .unwrap();
        let result2 = pipeline
            .process(&img, ProtectionLevel::Standard, &ctx2)
            .unwrap();

        let rgba1 = result1.to_rgba8();
        let rgba2 = result2.to_rgba8();

        assert_ne!(
            rgba1.as_raw(),
            rgba2.as_raw(),
            "Different seeds should produce different output"
        );
    }

    #[cfg(feature = "parallel")]
    #[test]
    fn test_parallel_processing() {
        let images: Vec<DynamicImage> = (0..4).map(|_| DynamicImage::new_rgb8(16, 16)).collect();

        let ctx = ProtectionContext::default().with_seed(42);

        let results = process_images_parallel(&images, ProtectionLevel::Standard, &ctx).unwrap();

        assert_eq!(results.len(), 4);
    }

    #[test]
    fn test_metadata_extraction() {
        let img = DynamicImage::new_rgb8(32, 32);

        let ctx = ProtectionContext::default()
            .with_seed(42)
            .with_format(ImageOutputFormat::Png);

        let metadata_protector = RightsMetadataProtector::new();
        let encoded = crate::util::image::encode_image(&img, image::ImageFormat::Png).unwrap();

        let protected_bytes = metadata_protector.apply_bytes(&encoded, &ctx).unwrap();

        let seed = RightsMetadataProtector::extract_seed_from_image(&protected_bytes);

        assert!(
            seed.is_some(),
            "Seed should be extractable from protected image"
        );
    }

    #[test]
    fn test_intensity_zero_no_change() {
        let pipeline = ProtectionPipeline::new();
        let img = DynamicImage::new_rgb8(16, 16);

        let ctx = ProtectionContext::default()
            .with_seed(42)
            .with_intensity(0.0);

        let result = pipeline
            .process(&img, ProtectionLevel::Disabled, &ctx)
            .unwrap();

        let original_bytes = img.to_rgba8();
        let result_bytes = result.to_rgba8();

        assert_eq!(original_bytes.as_raw(), result_bytes.as_raw());
    }

    #[test]
    fn test_max_dimension_validation() {
        let pipeline = ProtectionPipeline::new();
        let img = DynamicImage::new_rgb8(1000, 1000);

        let ctx = ProtectionContext::default()
            .with_seed(42)
            .with_max_dimension(512);

        let result = pipeline.process(&img, ProtectionLevel::Standard, &ctx);

        assert!(
            result.is_err(),
            "Should fail when image exceeds max dimension"
        );
    }

    #[test]
    fn test_max_dimension_validation_process_bytes() {
        use image::ImageEncoder;

        let img = DynamicImage::new_rgb8(1000, 1000);
        let mut buffer = Vec::new();
        {
            let encoder = image::codecs::png::PngEncoder::new(&mut buffer);
            let rgb = img.to_rgb8();
            encoder
                .write_image(&rgb, 1000, 1000, image::ExtendedColorType::Rgb8)
                .unwrap();
        }

        let ctx = ProtectionContext::default()
            .with_seed(42)
            .with_max_dimension(512);

        let result = process_image_bytes(&buffer, ProtectionLevel::Standard, &ctx);

        assert!(
            result.is_err(),
            "Should fail when image exceeds max dimension via process_bytes"
        );
    }

    #[test]
    fn pipeline_process_bytes_preserves_detected_jpeg_format() {
        let pipeline = ProtectionPipeline::new();
        let img = DynamicImage::new_rgb8(64, 64);
        let jpeg_bytes = crate::util::image::encode_image(&img, image::ImageFormat::Jpeg).unwrap();

        let ctx = ProtectionContext::new(0.5, 42);
        let protected = pipeline
            .process_bytes(&jpeg_bytes, ProtectionLevel::Standard, &ctx)
            .unwrap();

        assert!(
            protected.starts_with(&[0xFF, 0xD8, 0xFF]),
            "direct byte pipeline should preserve detected JPEG output format"
        );
    }

    #[test]
    fn light_process_bytes_validates_max_dimension() {
        use image::ImageEncoder;

        let img = DynamicImage::new_rgb8(1000, 1000);
        let mut buffer = Vec::new();
        {
            let encoder = image::codecs::png::PngEncoder::new(&mut buffer);
            let rgb = img.to_rgb8();
            encoder
                .write_image(&rgb, 1000, 1000, image::ExtendedColorType::Rgb8)
                .unwrap();
        }

        let ctx = ProtectionContext::default()
            .with_seed(42)
            .with_max_dimension(512);
        let result = process_image_bytes(&buffer, ProtectionLevel::Light, &ctx);

        assert!(
            result.is_err(),
            "Light byte processing should enforce max_dimension"
        );
    }

    #[test]
    fn light_process_bytes_can_convert_png_to_jpeg() {
        use image::ImageEncoder;

        let img = DynamicImage::new_rgb8(64, 64);
        let mut png_bytes = Vec::new();
        {
            let encoder = image::codecs::png::PngEncoder::new(&mut png_bytes);
            let rgb = img.to_rgb8();
            encoder
                .write_image(&rgb, 64, 64, image::ExtendedColorType::Rgb8)
                .unwrap();
        }

        let ctx = ProtectionContext::new(0.5, 42).with_format(ImageOutputFormat::Jpeg);
        let protected = process_image_bytes(&png_bytes, ProtectionLevel::Light, &ctx).unwrap();

        assert!(
            protected.starts_with(&[0xFF, 0xD8, 0xFF]),
            "Light byte processing should convert PNG input to requested JPEG output"
        );
    }

    #[test]
    fn process_request_metadata_only_png() {
        use image::ImageEncoder;

        let img = DynamicImage::new_rgb8(64, 64);
        let mut png_bytes = Vec::new();
        {
            let encoder = image::codecs::png::PngEncoder::new(&mut png_bytes);
            let rgb = img.to_rgb8();
            encoder
                .write_image(&rgb, 64, 64, image::ExtendedColorType::Rgb8)
                .unwrap();
        }

        let notice = RightsNotice::default();
        let request = ProtectionRequest::metadata_only(notice, RightsPolicy::Unspecified);
        let result = process_request_bytes(&png_bytes, &request);
        assert!(
            result.is_ok(),
            "Metadata-only PNG processing should succeed"
        );

        let output = result.unwrap();
        assert!(
            output.starts_with(&[0x89, 0x50, 0x4E, 0x47]),
            "Output should be PNG"
        );
    }

    #[test]
    fn process_request_metadata_only_jpeg() {
        use image::ImageEncoder;

        let img = DynamicImage::new_rgb8(64, 64);
        let mut jpeg_bytes = Vec::new();
        {
            let encoder = image::codecs::jpeg::JpegEncoder::new_with_quality(&mut jpeg_bytes, 90);
            let rgb = img.to_rgb8();
            encoder
                .write_image(&rgb, 64, 64, image::ExtendedColorType::Rgb8)
                .unwrap();
        }

        let notice = RightsNotice::default();
        let request = ProtectionRequest::metadata_only(notice, RightsPolicy::Unspecified);
        let result = process_request_bytes(&jpeg_bytes, &request);
        assert!(
            result.is_ok(),
            "Metadata-only JPEG processing should succeed"
        );

        let output = result.unwrap();
        assert!(
            output.starts_with(&[0xFF, 0xD8, 0xFF]),
            "Output should be JPEG"
        );
    }

    #[test]
    fn process_request_rejects_hmac_without_key() {
        let notice = RightsNotice::default();
        let request = ProtectionRequest::new(
            notice,
            RightsPolicy::ProhibitedAiMlTraining,
            ProtectionChannels::authenticated(),
        );
        let input_format = ImageOutputFormat::Png;
        let result = resolve_request(&request, input_format);
        assert!(result.is_err(), "HMAC without key should fail resolution");
    }

    #[test]
    fn process_request_rejects_hmac_with_disabled_marker() {
        let notice = RightsNotice::default();
        let request = ProtectionRequest::new(
            notice,
            RightsPolicy::ProhibitedAiMlTraining,
            ProtectionChannels {
                rights_metadata: true,
                hidden_marker: HiddenMarkerMode::Disabled,
                authentication: AuthenticationMode::Hmac,
            },
        )
        .with_mac_key(b"test-key".to_vec());

        let input_format = ImageOutputFormat::Png;
        let result = resolve_request(&request, input_format);
        assert!(result.is_err(), "HMAC with disabled marker should fail");
    }

    #[test]
    fn process_request_preserves_png_format() {
        use image::ImageEncoder;

        let img = DynamicImage::new_rgb8(32, 32);
        let mut png_bytes = Vec::new();
        {
            let encoder = image::codecs::png::PngEncoder::new(&mut png_bytes);
            let rgb = img.to_rgb8();
            encoder
                .write_image(&rgb, 32, 32, image::ExtendedColorType::Rgb8)
                .unwrap();
        }

        let notice = RightsNotice::default();
        let request = ProtectionRequest::metadata_only(notice, RightsPolicy::Unspecified);
        let output = process_request_bytes(&png_bytes, &request).unwrap();
        assert!(output.starts_with(&[0x89, 0x50, 0x4E, 0x47]));
        assert!(output.len() >= png_bytes.len());
    }

    #[test]
    fn preset_legal_notice_is_metadata_only() {
        let preset = ProtectionPreset::LegalNotice;
        let channels = preset.to_channels();
        assert!(!channels.has_stego());
        assert!(channels.rights_metadata);
        assert!(!preset.requires_mac_key());
    }

    #[test]
    fn preset_legal_notice_with_stego_has_marker() {
        let preset = ProtectionPreset::LegalNoticeWithStego;
        let channels = preset.to_channels();
        assert!(channels.has_stego());
        assert!(channels.rights_metadata);
        assert!(!preset.requires_mac_key());
    }

    #[test]
    fn preset_authenticated_requires_mac() {
        let preset = ProtectionPreset::AuthenticatedProvenance;
        assert!(preset.requires_mac_key());
        let channels = preset.to_channels();
        assert!(channels.has_stego());
        assert!(matches!(channels.authentication, AuthenticationMode::Hmac));
    }

    #[test]
    fn preset_maximal_requires_mac() {
        let preset = ProtectionPreset::Maximal;
        assert!(preset.requires_mac_key());
        let channels = preset.to_channels();
        assert!(channels.has_stego());
        assert!(matches!(channels.authentication, AuthenticationMode::Hmac));
    }

    #[test]
    fn from_preset_sets_channels() {
        let notice = RightsNotice::default();
        let req = ProtectionRequest::from_preset(
            ProtectionPreset::LegalNotice,
            notice,
            RightsPolicy::ProhibitedAiMlTraining,
        );
        assert!(!req.channels().has_stego());
        assert!(req.channels().rights_metadata);
    }

    #[test]
    fn process_request_with_report_metadata_only() {
        use image::ImageEncoder;

        let img = DynamicImage::new_rgb8(32, 32);
        let mut png_bytes = Vec::new();
        {
            let encoder = image::codecs::png::PngEncoder::new(&mut png_bytes);
            let rgb = img.to_rgb8();
            encoder
                .write_image(&rgb, 32, 32, image::ExtendedColorType::Rgb8)
                .unwrap();
        }

        let notice = RightsNotice::default();
        let request =
            ProtectionRequest::metadata_only(notice, RightsPolicy::ProhibitedAiMlTraining);
        let (output, report) = process_request_bytes_with_report(&png_bytes, &request).unwrap();

        assert!(report.metadata_injected);
        assert!(!report.stego_attempted);
        assert!(!report.format_transcoded);
        assert!(report.effective_dmi.is_some());
        assert!(output.starts_with(&[0x89, 0x50, 0x4E, 0x47]));
    }

    #[test]
    fn rights_policy_dmi_roundtrip() {
        let policies = [
            RightsPolicy::Unspecified,
            RightsPolicy::Allowed,
            RightsPolicy::ProhibitedAiMlTraining,
            RightsPolicy::ProhibitedGenerativeAiTraining,
            RightsPolicy::ProhibitedExceptSearchIndexing,
            RightsPolicy::ProhibitedAllDataMining,
            RightsPolicy::ProhibitedSeeConstraints,
        ];
        for policy in &policies {
            let dmi = DmiValue::from(*policy);
            let back = RightsPolicy::from_dmi_value(dmi);
            assert_eq!(&back, policy, "Roundtrip failed for {:?}", policy);
        }
    }

    #[test]
    fn rights_policy_to_dmi_unspecified_is_none() {
        assert!(RightsPolicy::Unspecified.to_dmi_value().is_none());
    }

    #[test]
    fn rights_policy_to_dmi_allowed_is_some() {
        assert_eq!(
            RightsPolicy::Allowed.to_dmi_value(),
            Some(DmiValue::Allowed)
        );
    }

    #[test]
    fn protection_level_to_request_disabled() {
        let notice = RightsNotice::default();
        let req = ProtectionLevel::Disabled.to_request(notice, RightsPolicy::Unspecified);
        assert!(!req.channels().rights_metadata);
        assert!(!req.channels().has_stego());
    }

    #[test]
    fn protection_level_to_request_light() {
        let notice = RightsNotice::default();
        let req = ProtectionLevel::Light.to_request(notice, RightsPolicy::ProhibitedAiMlTraining);
        assert!(req.channels().rights_metadata);
        assert!(req.channels().has_stego());
    }

    #[test]
    fn protection_level_to_request_standard() {
        let notice = RightsNotice::default();
        let req = ProtectionLevel::Standard.to_request(notice, RightsPolicy::Allowed);
        assert!(req.channels().rights_metadata);
        assert!(req.channels().has_stego());
    }

    #[test]
    fn request_from_legacy_light_default_policy_is_unspecified() {
        let ctx = ProtectionContext::new(0.5, 42);
        let request = request_from_legacy(ProtectionLevel::Light, &ctx);
        assert_eq!(request.policy(), RightsPolicy::Unspecified);
        assert!(matches!(
            request.channels().hidden_marker,
            HiddenMarkerMode::SeedOnly
        ));
    }

    #[test]
    fn request_from_legacy_light_with_tile_size_is_seed_only() {
        let ctx = ProtectionContext::new(0.5, 42).with_tile_size(64);
        let request = request_from_legacy(ProtectionLevel::Light, &ctx);
        assert!(matches!(
            request.channels().hidden_marker,
            HiddenMarkerMode::SeedOnly
        ));
    }

    #[test]
    fn request_from_legacy_standard_with_tile_size_is_tiled() {
        let ctx = ProtectionContext::new(0.5, 42).with_tile_size(64);
        let request = request_from_legacy(ProtectionLevel::Standard, &ctx);
        assert!(matches!(
            request.channels().hidden_marker,
            HiddenMarkerMode::Tiled { tile_size: 64 }
        ));
    }

    #[test]
    #[allow(deprecated)]
    fn request_from_legacy_explicit_dmi_overrides_default() {
        let ctx = ProtectionContext::new(0.5, 42).with_dmi(DmiValue::Allowed);
        let request = request_from_legacy(ProtectionLevel::Light, &ctx);
        assert_eq!(request.policy(), RightsPolicy::Allowed);
        assert_eq!(request.notice().dmi(), Some(DmiValue::Allowed));
    }

    #[test]
    fn request_from_legacy_explicit_redundancy_preserved() {
        let ctx = ProtectionContext::new(0.5, 42).with_stego_redundancy(7);
        let request = request_from_legacy(ProtectionLevel::Standard, &ctx);
        let plan = resolve_request(&request, ImageOutputFormat::Png).unwrap();
        assert_eq!(plan.effective_redundancy(), 7);
    }

    #[test]
    fn request_from_legacy_content_hash_preserved() {
        let hash = [0xDE, 0xAD, 0xBE, 0xEF];
        let ctx = ProtectionContext::new(0.5, 42).with_content_hash(hash);
        let request = request_from_legacy(ProtectionLevel::Standard, &ctx);
        assert_eq!(request.processing().content_hash, Some(hash));
        let plan = resolve_request(&request, ImageOutputFormat::Png).unwrap();
        assert_eq!(plan.processing().content_hash, Some(hash));
    }

    #[test]
    fn request_from_legacy_timestamp_override_preserved() {
        let timestamp = "2025-06-15T10:00:00Z";
        let ctx = ProtectionContext::new(0.5, 42)
            .with_legal_metadata(LegalMetadata::new().with_copyright_holder("Owner"))
            .with_timestamp_override(timestamp);
        let request = request_from_legacy(ProtectionLevel::Standard, &ctx);
        assert_eq!(request.timestamp_override(), Some(timestamp));
        let plan = resolve_request(&request, ImageOutputFormat::Png).unwrap();
        assert_eq!(plan.effective_notice().notice_applied_at(), Some(timestamp));
    }

    #[test]
    fn request_from_legacy_legal_claims_none_auto_includes_supplied_metadata() {
        let ctx = ProtectionContext::new(0.5, 42)
            .with_legal_metadata(LegalMetadata::new().with_copyright_holder("Owner"));
        let request = request_from_legacy(ProtectionLevel::Standard, &ctx);
        let plan = resolve_request(&request, ImageOutputFormat::Png).unwrap();
        assert_eq!(plan.effective_notice().copyright_holder(), Some("Owner"));
        assert!(plan.legal_metadata().is_some());
    }

    #[test]
    #[allow(deprecated)]
    fn request_from_legacy_legal_claims_false_excludes_claims() {
        let ctx = ProtectionContext::new(0.5, 42)
            .with_legal_metadata(LegalMetadata::new().with_copyright_holder("Owner"))
            .with_legal_claims(false);
        let request = request_from_legacy(ProtectionLevel::Standard, &ctx);
        let plan = resolve_request(&request, ImageOutputFormat::Png).unwrap();
        assert_eq!(plan.effective_notice().copyright_holder(), None);
        assert!(plan.legal_metadata().is_none());
    }

    #[test]
    fn request_from_legacy_resource_limits_preserved() {
        let limits = ResourceLimits::builder()
            .max_payload_bytes(111)
            .max_tile_extraction_origins(3)
            .build();
        let ctx = ProtectionContext::new(0.5, 42).with_resource_limits(limits.clone());
        let request = request_from_legacy(ProtectionLevel::Standard, &ctx);
        let request_limits = request
            .resource_limits()
            .expect("legacy limits should be present");
        assert_eq!(
            request_limits.max_payload_bytes(),
            limits.max_payload_bytes()
        );
        assert_eq!(
            request_limits.max_tile_extraction_origins(),
            limits.max_tile_extraction_origins()
        );
        let plan = resolve_request(&request, ImageOutputFormat::Png).unwrap();
        assert_eq!(plan.resource_limits().max_payload_bytes(), 111);
        assert_eq!(plan.resource_limits().max_tile_extraction_origins(), 3);
    }

    #[test]
    fn preset_to_channels_metadata_only() {
        let channels = ProtectionPreset::LegalNotice.to_channels();
        assert!(!channels.has_stego());
        assert!(channels.rights_metadata);
    }

    #[test]
    fn preset_to_channels_with_stego() {
        let channels = ProtectionPreset::LegalNoticeWithStego.to_channels();
        assert!(channels.has_stego());
    }

    #[test]
    fn preset_to_channels_authenticated() {
        let channels = ProtectionPreset::AuthenticatedProvenance.to_channels();
        assert!(channels.has_stego());
        assert!(matches!(channels.authentication, AuthenticationMode::Hmac));
    }

    fn plan078_textured_png_bytes(size: u32) -> Vec<u8> {
        use image::ImageEncoder;
        let img = image::DynamicImage::new_rgb8(size, size);
        let mut buffer = Vec::new();
        let encoder = image::codecs::png::PngEncoder::new(&mut buffer);
        let rgb = img.to_rgb8();
        encoder
            .write_image(&rgb, size, size, image::ExtendedColorType::Rgb8)
            .unwrap();
        buffer
    }

    fn plan078_hidden_marker_request() -> ProtectionRequest {
        let notice = RightsNotice::new().with_copyright_holder("Plan 078");
        ProtectionRequest::with_hidden_marker(notice, RightsPolicy::ProhibitedAiMlTraining)
            .with_seed(42)
            .with_intensity(0.5)
    }

    #[test]
    fn plan078_png_marker_performs_single_pixel_decode() {
        let png_bytes = plan078_textured_png_bytes(128);
        crate::util::image::reset_load_decode_count();
        let output = process_request_bytes(&png_bytes, &plan078_hidden_marker_request());
        assert!(output.is_ok());
        assert_eq!(crate::util::image::load_decode_count(), 1);
    }

    #[test]
    fn plan078_metadata_only_png_performs_no_pixel_decode() {
        let png_bytes = plan078_textured_png_bytes(128);
        let notice = RightsNotice::new().with_copyright_holder("Plan 078");
        let request =
            ProtectionRequest::metadata_only(notice, RightsPolicy::ProhibitedAiMlTraining);
        crate::util::image::reset_load_decode_count();
        let output = process_request_bytes(&png_bytes, &request);
        assert!(output.is_ok());
        assert_eq!(crate::util::image::load_decode_count(), 0);
    }

    #[test]
    fn plan078_tiled_png_request_verifies_with_single_decode() {
        let png_bytes = plan078_textured_png_bytes(256);
        let notice = RightsNotice::new().with_copyright_holder("Plan 078");
        let channels = ProtectionChannels {
            rights_metadata: true,
            hidden_marker: HiddenMarkerMode::Tiled { tile_size: 64 },
            authentication: AuthenticationMode::None,
        };
        let request =
            ProtectionRequest::new(notice, RightsPolicy::ProhibitedAiMlTraining, channels)
                .with_seed(42)
                .with_intensity(0.5);
        crate::util::image::reset_load_decode_count();
        let output = process_request_bytes(&png_bytes, &request);
        assert!(output.is_ok());
        let protected = output.unwrap();
        assert_eq!(crate::util::image::load_decode_count(), 1);
        assert_eq!(
            verify_image_bytes(&protected, &[]),
            VerificationStatus::Verified
        );
    }

    #[test]
    fn plan078_malformed_input_still_fails_closed() {
        let garbage = b"not an image at all";
        crate::util::image::reset_load_decode_count();
        assert!(process_request_bytes(garbage, &plan078_hidden_marker_request()).is_err());
        let notice = RightsNotice::new().with_copyright_holder("Plan 078");
        let request =
            ProtectionRequest::metadata_only(notice, RightsPolicy::ProhibitedAiMlTraining);
        assert!(process_request_bytes(garbage, &request).is_err());
    }
}
